apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-password
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: postgres-password-k8s
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: nombre-del-secreto-en-gcp