{{- if and .Values.ingress.enabled (eq .Values.ingress.controller "generic") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "medplum.fullname" . }}-external
  namespace: {{ include "medplum.namespace" . }}
  labels:
    {{- include "medplum.labels" (dict "context" . "component" .Values.name "name" .Values.name) | nindent 4 }}
    {{- with .Values.ingress.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | default .Values.global.domain }}
      http:
        paths:
          {{- with .Values.ingress.extraPaths }}
            {{- tpl (toYaml .) $ | nindent 10 }}
          {{- end }}
          - path: {{ .Values.ingress.path }}
            pathType: {{ $.Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "medplum.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default $.Values.ingress.path .path }}
            pathType: {{ default $.Values.ingress.pathType .pathType }}
            backend:
              service:
                name: {{ include "medplum.fullname" $ }}
                port:
                  number: {{ .Values.service.port }}
    {{- end }}
    {{- with .Values.ingress.extraRules }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  {{- if or .Values.ingress.tls .Values.ingress.extraTls }}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
      - {{ .Values.ingress.hostname | default .Values.global.domain }}
      {{- range .Values.ingress.extraHosts }}
        {{- if .name }}
      -  {{ .name }}
        {{- end }}
      {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
    {{- end }}
    {{- with .Values.ingress.extraTls }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
