apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: {{ .Values.namespace }}
spec:
  provider:
    gcpsm:
      projectID: medplum-zencore
      auth:
        workloadIdentity:
          clusterLocation: us-west1     # Replace with your cluster location
          clusterName: medplum-gke      # Replace with your cluster name
          serviceAccountRef:
            name: medplum-server
            namespace: {{ .Values.namespace }}