apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: "medplum-zencore"
      auth:
        type: "workloadIdentity"
        workloadIdentity:
          clusterLocation: "us-west1"      # Replace with your cluster location
          clusterName: "medplum-gke"       # Replace with your cluster name
          # clusterProjectID: "medplum-zencore"  # Optional if different from projectID
          serviceAccountRef:
            name: external-secrets
            namespace: default