apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectId: medplum-zencore
  authentication:
    type: workloadIdentity
    serviceAccountRef:
      name: external-secrets-ksa
      namespace: external-secrets