{{ if .Values.externalGateway }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "medplum.fullname" . }}-external
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "medplum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "medplum.selectorLabels" . | nindent 4 }}
{{ end }}