{{ if .Values.externalGateway }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "medplum.fullname" . }}
  namespace: {{ include "medplum.namespace" . }}
  labels:
    {{- include "medplum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
      name: http
  selector:
    {{- include "medplum.selectorLabels" . | nindent 4 }}
{{ end }}