{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
namespace: {{ .Values.namespace }}
metadata:
  name: {{ include "medplum.serviceAccountName" . }}
  labels:
    {{- include "medplum.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
