{{- if and (eq .Values.global.cloudProvider "gcp") (eq .Values.ingress.deploy true) }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ include "medplum.fullname" . }}
  namespace: {{ include  "medplum.namespace" . }}
  labels:
    {{- include "medplum.labels" . | nindent 4 }}
spec:
  sslPolicy: "medplum-ssl-policy"
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
{{- end }}