apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "medplum.serviceAccountName" . }}
  namespace: {{ include "medplum.namespace" . }}
  labels:
    {{- include "medplum.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if eq .Values.global.cloudProvider "gcp" }}
automountServiceAccountToken: true
{{- end }}
