# PostgreSQL Database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: medplum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: medplum
            - name: POSTGRES_USER
              value: medplum
            - name: POSTGRES_PASSWORD
              value: medplum
          args:
            - "postgres"
            - "-c"
            - "listen_addresses=*"
            - "-c"
            - "statement_timeout=60000"
            - "-c"
            - "default_transaction_isolation=REPEATABLE READ"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: medplum
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
# Redis Cache
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: medplum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          command:
            - "redis-server"
            - "--requirepass"
            - "medplum"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: medplum
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
