# Medplum App (Frontend)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medplum-app
  namespace: medplum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medplum-app
  template:
    metadata:
      labels:
        app: medplum-app
    spec:
      containers:
        - name: medplum-app
          image: medplum/medplum-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: MEDPLUM_BASE_URL
              value: "http://localhost:8103/"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: medplum-app
  namespace: medplum
spec:
  type: LoadBalancer
  selector:
    app: medplum-app
  ports:
    - port: 3000
      targetPort: 3000
