# Medplum configuration for Docker Desktop Kubernetes
global:
  storageClass: "hostpath"
  cloudProvider: "local"

serviceAccount:
  annotations: {}

deployment:
  env:
    # Server configuration
    - name: MEDPLUM_PORT
      value: "8103"
    - name: MEDPLUM_BASE_URL
      value: "http://localhost:8103/"
    - name: MEDPLUM_APP_BASE_URL
      value: "http://localhost:3000/"
    - name: MEDPLUM_STORAGE_BASE_URL
      value: "http://localhost:8103/storage/"

    # Database configuration
    - name: MEDPLUM_DATABASE_HOST
      value: "postgres"
    - name: MEDPLUM_DATABASE_PORT
      value: "5432"
    - name: MEDPLUM_DATABASE_DBNAME
      value: "medplum"
    - name: MEDPLUM_DATABASE_USERNAME
      value: "medplum"
    - name: MEDPLUM_DATABASE_PASSWORD
      value: "medplum"

    # Redis configuration
    - name: MEDPLUM_REDIS_HOST
      value: "redis"
    - name: MEDPLUM_REDIS_PORT
      value: "6379"
    - name: MEDPLUM_REDIS_PASSWORD
      value: "medplum"

    # Storage and security (demo values for local dev)
    - name: MEDPLUM_BINARY_STORAGE
      value: "file:/tmp/medplum-files/"
    - name: MEDPLUM_SIGNING_KEY_ID
      value: "my-key-id"
    - name: MEDPLUM_SIGNING_KEY_PASSPHRASE
      value: "top_secret"
    - name: MEDPLUM_SIGNING_KEY
      value: "-----BEGIN RSA PRIVATE KEY-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: DES-EDE3-CBC,4C2E1B45FFF24610\n\n0SOZn3P0Bd9lZgv2eSWWLMQ4JqxhbJ+dWM+V1TtSwqxe3VP24z4bys5VRpmsEpqn\nROKxdXCeqAbYsLo8V9dOQvwaxo2TTWFgUFj7sQYklyr1g5S9+KCp+1B/5E7UgNDd\nhXA2u4uhz6Bck0mTPwoy3oHjNUaNBZilMdwiR3qeiGYC0DyX69+IJgwFUTt2a1jc\nU5aUyellGYa47QRZcePgyk7Cl4FcBW9YA0pS4rNpO4wNVN6GGuZti4c0Y3PHXSRE\nDse95ZN9iWBtufjpjk4s8MX0rzqMWcjbAhTs2N5YBgKsv2czm5YMdXsYH6tGL7a1\nPyNia0r1AnHAD3pK+vzaZGaLrvubZikrt7dr+Tp1U45b2YaZlMMaXwGU6WEK7kwr\n4sbl9hqQf/+oqBAdyJIgxIhFumK+ukUIlCV+b/XUuoatDXD127JwEyEM78Nzg5Bc\n/bKGEo9uehXpuIi0jp1BtegUIkfoV543PZZgslGVdzq0vXOir+PiHJBLlbWXXSAb\nEWKOQW2/bZ8JIHhi3Ag7KDlTVF1XetJ2TqYOOP9izfMp4lJ2vLtkH7P+jEKG8z6b\nurnXYkDWYEbzhG1frEssVQN0GP3wdyEK+n6LBCuj52Uje/M7LwahPX6dJRYPOpL9\nbApSNNJLahRRQREHp1wqEWism3r4+yRa4ha/BGc4dfKTsUtJEiHqdWvDzomN5C6A\nC7u3zjUv3ZZLoCLCbBUsiVdlJZJ5u/ymky5LKVbsscmZj93HE7/FL56I17bmTlDo\npvkJWk9SmVXvs3lwMMBRbykj974ZWEMw9EjCoP9rDJ0UNsy2kVRFfXoPMKL5S01D\niBRVSZB7k7qJofGtlBpDfooHOw4uAJ/6A0l8vpOm/Vpk8tdiRLL/RuzEKz5G3ltm\nrXPn83avfNc5+EvaM8IIKyPTvHegE5XszGK3NNlzUO1Ydze/xQPhdrp4QYFzJOuB\nXVIazLeXSJ5EjJ1ylWAWgNzsx+42NWeA2CZAZz+IJFw6C2iHEB8f8Nw6iJmFfm3I\nWsrvCRbuwIsW9fjtHTpOCCpxXu5EcvN5BKwFXeBatB7xqR6EnPbk6xDxZdroEKhH\nEZU4PlHu+BwTKKCwa4Ynwn1Qpu453qgNzaxgHLbdFipW5/AkreNWK5Il+5Bl8G90\no/MhO66eBXv3JbOtMUAqs9+Qyl5K1TaNqbStWmsiq+36Niz4ZRg7L/7W6zjG/hTH\npignoDyJYPjFFQ/sTsTUv0oKVI6KIYFlIHBDnGGnH09926sd+U/isSeMDP+Qa32m\nhHzScmDPsdyjdFsdXsJjZHe7mqCijGXu/LW4CoWoqln4y29c5BMJazwnIwegrLjJ\nQeW6InUhGZLy+uJbs1ZWxlqzOmMoTx2VVgoABdOHn/mQEC/AreUdvPMkVVYEuxel\nmAMOoefncx/EPxn7gY2SrEdmSnk9VuzR30KMC1qSw196QbQHR1G2vxKcXPwe/LH9\n7Pa0gwwqCaS2ggYt5Rvlxm7DeBIGHzGtPILnl1qyVGaqn64244JeLi9bY/O+E+uq\nBSgQmt2NwPK2RQgzzt/ETUXoOFHKiwS1v2Vp4H2PPDI8CzvlRralsQ==\n-----END RSA PRIVATE KEY-----"
    # Basic settings
    - name: MEDPLUM_SUPPORT_EMAIL
      value: '"Demo" <demo@example.com>'
    - name: MEDPLUM_ALLOWED_ORIGINS
      value: "*"
    - name: MEDPLUM_INTROSPECTION_ENABLED
      value: "true"
    - name: MEDPLUM_RECAPTCHA_SITE_KEY
      value: "6LfHdsYdAAAAAC0uLnnRrDrhcXnziiUwKd8VtLNq"
    - name: MEDPLUM_RECAPTCHA_SECRET_KEY
      value: "6LfHdsYdAAAAAH9dN154jbJ3zpQife3xaiTvPChL"
    - name: MEDPLUM_PRE_COMMIT_SUBSCRIPTIONS_ENABLED
      value: "true"
    - name: MEDPLUM_FISSION_NAMESPACE
      value: "default"
    - name: MEDPLUM_FISSION_ROUTER_HOST
      value: "router.fission.svc.cluster.local"
    - name: MEDPLUM_FISSION_ROUTER_PORT
      value: "80"
    - name: MEDPLUM_FISSION_ENVIRONMENT_NAME
      value: "nodejs"
    - name: MEDPLUM_FISSION_FIELD_MANAGER
      value: "medplum-fission-example"

# Expose service automatically via LoadBalancer
service:
  type: LoadBalancer
  port: 8103

# Disable ingress for local development
ingress:
  deploy: false
