FROM --platform=linux/amd64 node:18-slim

RUN apt update
RUN apt install -y git

ENV NODE_ENV development

workdir /usr/app

#RUN git clone https://github.com/medplum/medplum.git .
COPY package.json .
COPY package-lock.json .
COPY api-extractor.json .
COPY biome.json .
COPY tsconfig.json .
COPY turbo.json .
COPY tsdoc.json .
COPY dangerfile.ts .
COPY packages packages/
COPY postgres postgres/
COPY scripts scripts/

RUN npm install

RUN npm run build -- --filter=@medplum/server

#RUN sed -i "45 i      ssl: { rejectUnauthorized: false }," packages/server/dist/database.js

EXPOSE 5000 8103
ENTRYPOINT [ "node", "packages/server/dist/index.js", "aws:us-east-2:/medplum/dev/" ]
