{{- if eq .Values.global.cloudProvider "gcp" }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "medplum.fullname" . }}
  namespace: {{ include  "medplum.namespace" . }}
  labels:
    {{- include "medplum.labels" . | nindent 4 }}
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
{{- end }}