{{- if and .Values.ingress.enabled (eq .Values.global.cloudProvider "gcp") }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "medplum.fullname" . }}
  namespace: {{ include "medplum.namespace" . }}
spec:
  domains:
    - {{ .Values.ingress.hostname | default .Values.global.domain }}
{{- end }}