apiVersion: v1
kind: Service
metadata:
  name: {{ include "medplum.fullname" . }}-service
  namespace: {{ include "medplum.namespace" . }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"8103":"medplum-backendconfig"}}'
  labels:
    {{- include "medplum.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http-port
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "medplum.selectorLabels" . | nindent 4 }}
