{{- if eq (include "medplum.ingress.enabled" . | trim) "true" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "medplum.fullname" . }}
  labels:
    {{- include "medplum.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with include "medplum.ingress.className" . | trim }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with include "medplum.ingress.tls" . | trim }}
  tls:
    {{- . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ include "medplum.ingress.host" . | required "ingress.host is required when ingress.enabled" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "medplum.fullname" . }}-service
                port:
                  number: {{ .Values.service.port | default 80 }}
{{- end }}
