apiVersion: v1
kind: Secret
metadata:
  name: {{ include "medplum.fullname" . }}-secrets
type: Opaque
stringData:
  # Server configuration
  {{- with .Values.config.server }}
  MEDPLUM_SIGNING_KEY_PASSPHRASE: {{ .signingKeyPassphrase | quote }}
  MEDPLUM_SIGNING_KEY: {{ .signingKey | quote }}
  MEDPLUM_GOOGLE_CLIENT_SECRET: {{ .googleClientSecret | quote }}
  MEDPLUM_RECAPTCHA_SECRET_KEY: {{ .recaptchaSecretKey | quote }}
  {{- end }}

  # Database configuration
  {{- with .Values.config.database }}
  MEDPLUM_DATABASE_PASSWORD: {{ .password | quote }}
  {{- end }}

  # Redis configuration
  {{- with .Values.config.redis }}
  MEDPLUM_REDIS_PASSWORD: {{ .password | quote }}
  {{- end }}
