# Default values for medplum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  cloudProvider: gcp # Supported values: gcp, azure
  configSource:
    # Examples:
    # type: "env"
    # type: "aws:region:parameterName"
    # type: "gcp:projectId:secretId"
    # type: "azure:keyVaultURL:secretName"
    type: "env"  # Default to env
 
serviceAccount: 
  annotations:
    iam.gke.io/gcp-service-account: [MY_GCP_SERVICE_ACCOUNT] # Your Google Cloud Platform service account e.i: medplum-server@[MY_PROJECT_ID].iam.gserviceaccount.com
    # azure.workload.identity/client-id: "7f644391-4b27-4f76-8427-17bae90d7ee8" # Azure Managed Identity Client ID

namespace: medplum

deployment:
  replicaCount: 1
  image:
    repository: medplum/medplum-server
    tag: latest
  env:
    # - name: SQL_DEBUG
    #   value: '*'
  resources:
    requests:
      memory: "1Gi"
    limits:
      memory: "2Gi"
  autoscaling:
    enabled: true

service: {}

ingress:
  deploy: true
  domain: [MY_DOMAIN] # Your domain name
  tlsSecretName: [TLS_SECRET_NAME] # Azure only
  