import { Router } from 'express';
import { asyncWrap } from '../async';
import { authenticateToken } from '../oauth/middleware';
import { getRateLimiter } from '../ratelimit';
import { changePasswordHandler, changePasswordValidators } from './changepassword';
import { googleHandler, googleValidators } from './google';
import { loginHandler, loginValidators } from './login';
import { meHandler } from './me';
import { newPatientHandler, newPatientValidators } from './newpatient';
import { newProjectHandler, newProjectValidators } from './newproject';
import { newUserHandler, newUserValidators } from './newuser';
import { profileHandler, profileValidators } from './profile';
import { resetPasswordHandler, resetPasswordValidators } from './resetpassword';
import { scopeHandler, scopeValidators } from './scope';
import { setPasswordHandler, setPasswordValidators } from './setpassword';

export const authRouter = Router();
authRouter.use(getRateLimiter());
authRouter.get('/me', authenticateToken, asyncWrap(meHandler));
authRouter.post('/newuser', newUserValidators, asyncWrap(newUserHandler));
authRouter.post('/newproject', newProjectValidators, asyncWrap(newProjectHandler));
authRouter.post('/newpatient', newPatientValidators, asyncWrap(newPatientHandler));
authRouter.post('/login', loginValidators, asyncWrap(loginHandler));
authRouter.post('/profile', profileValidators, asyncWrap(profileHandler));
authRouter.post('/scope', scopeValidators, asyncWrap(scopeHandler));
authRouter.post('/changepassword', changePasswordValidators, asyncWrap(changePasswordHandler));
authRouter.post('/resetpassword', resetPasswordValidators, asyncWrap(resetPasswordHandler));
authRouter.post('/setpassword', setPasswordValidators, asyncWrap(setPasswordHandler));
authRouter.post('/google', googleValidators, asyncWrap(googleHandler));
