/*
 * Generated by @medplum/generator
 * Do not edit manually.
 */

import { CodeableConcept } from './CodeableConcept';
import { Extension } from './Extension';
import { Identifier } from './Identifier';
import { Meta } from './Meta';
import { Narrative } from './Narrative';
import { Reference } from './Reference';
import { Resource } from './Resource';

/**
 * Describes a comparison of an immunization event against published
 * recommendations to determine if the administration is &quot;valid&quot; in
 * relation to those  recommendations.
 */
export interface ImmunizationEvaluation {

  /**
   * This is a ImmunizationEvaluation resource
   */
  readonly resourceType: 'ImmunizationEvaluation';

  /**
   * The logical id of the resource, as used in the URL for the resource.
   * Once assigned, this value never changes.
   */
  readonly id?: string;

  /**
   * The metadata about the resource. This is content that is maintained by
   * the infrastructure. Changes to the content might not always be
   * associated with version changes to the resource.
   */
  readonly meta?: Meta;

  /**
   * A reference to a set of rules that were followed when the resource was
   * constructed, and which must be understood when processing the content.
   * Often, this is a reference to an implementation guide that defines the
   * special rules along with other profiles etc.
   */
  readonly implicitRules?: string;

  /**
   * The base language in which the resource is written.
   */
  readonly language?: string;

  /**
   * A human-readable narrative that contains a summary of the resource and
   * can be used to represent the content of the resource to a human. The
   * narrative need not encode all the structured data, but is required to
   * contain sufficient detail to make it &quot;clinically safe&quot; for a human to
   * just read the narrative. Resource definitions may define what content
   * should be represented in the narrative to ensure clinical safety.
   */
  readonly text?: Narrative;

  /**
   * These resources do not have an independent existence apart from the
   * resource that contains them - they cannot be identified independently,
   * and nor can they have their own independent transaction scope.
   */
  readonly contained?: Resource[];

  /**
   * May be used to represent additional information that is not part of
   * the basic definition of the resource. To make the use of extensions
   * safe and manageable, there is a strict set of governance  applied to
   * the definition and use of extensions. Though any implementer can
   * define an extension, there is a set of requirements that SHALL be met
   * as part of the definition of the extension.
   */
  readonly extension?: Extension[];

  /**
   * May be used to represent additional information that is not part of
   * the basic definition of the resource and that modifies the
   * understanding of the element that contains it and/or the understanding
   * of the containing element's descendants. Usually modifier elements
   * provide negation or qualification. To make the use of extensions safe
   * and manageable, there is a strict set of governance applied to the
   * definition and use of extensions. Though any implementer is allowed to
   * define an extension, there is a set of requirements that SHALL be met
   * as part of the definition of the extension. Applications processing a
   * resource are required to check for modifier extensions.
   *
   * Modifier extensions SHALL NOT change the meaning of any elements on
   * Resource or DomainResource (including cannot change the meaning of
   * modifierExtension itself).
   */
  readonly modifierExtension?: Extension[];

  /**
   * A unique identifier assigned to this immunization evaluation record.
   */
  readonly identifier?: Identifier[];

  /**
   * Indicates the current status of the evaluation of the vaccination
   * administration event.
   */
  readonly status?: string;

  /**
   * The individual for whom the evaluation is being done.
   */
  readonly patient?: Reference;

  /**
   * The date the evaluation of the vaccine administration event was
   * performed.
   */
  readonly date?: Date | string;

  /**
   * Indicates the authority who published the protocol (e.g. ACIP).
   */
  readonly authority?: Reference;

  /**
   * The vaccine preventable disease the dose is being evaluated against.
   */
  readonly targetDisease?: CodeableConcept;

  /**
   * The vaccine administration event being evaluated.
   */
  readonly immunizationEvent?: Reference;

  /**
   * Indicates if the dose is valid or not valid with respect to the
   * published recommendations.
   */
  readonly doseStatus?: CodeableConcept;

  /**
   * Provides an explanation as to why the vaccine administration event is
   * valid or not relative to the published recommendations.
   */
  readonly doseStatusReason?: CodeableConcept[];

  /**
   * Additional information about the evaluation.
   */
  readonly description?: string;

  /**
   * One possible path to achieve presumed immunity against a disease -
   * within the context of an authority.
   */
  readonly series?: string;

  /**
   * Nominal position in a series.
   */
  readonly doseNumberPositiveInt?: number;

  /**
   * Nominal position in a series.
   */
  readonly doseNumberString?: string;

  /**
   * The recommended number of doses to achieve immunity.
   */
  readonly seriesDosesPositiveInt?: number;

  /**
   * The recommended number of doses to achieve immunity.
   */
  readonly seriesDosesString?: string;
}
