/*
 * Generated by @medplum/generator
 * Do not edit manually.
 */

import { Meta } from './Meta';
import { Reference } from './Reference';

export interface Project {

  /**
   * This is a Project resource
   */
  readonly resourceType: 'Project';

  /**
   * The logical id of the resource, as used in the URL for the resource.
   * Once assigned, this value never changes.
   */
  readonly id?: string;

  /**
   * The metadata about the resource. This is content that is maintained by
   * the infrastructure. Changes to the content might not always be
   * associated with version changes to the resource.
   */
  readonly meta?: Meta;

  /**
   * A reference to a set of rules that were followed when the resource was
   * constructed, and which must be understood when processing the content.
   * Often, this is a reference to an implementation guide that defines the
   * special rules along with other profiles etc.
   */
  readonly implicitRules?: string;

  /**
   * The base language in which the resource is written.
   */
  readonly language?: string;

  /**
   * A name associated with the Project.
   */
  readonly name?: string;

  /**
   * A summary, characterization or explanation of the Project.
   */
  readonly description?: string;

  /**
   * A name associated with the Project.
   */
  readonly owner?: Reference;
}
