/*
 * Generated by com.medplum.generator.Generator
 * Do not edit manually.
 */

package com.medplum.fhir.r4.types;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.json.Json;

import org.junit.Test;

public class AdverseEventSuspectEntityTest {

    @Test
    public void testConstructor() {
        assertNotNull(new AdverseEvent.AdverseEventSuspectEntity(Json.createObjectBuilder().build()));
    }

    @Test
    public void testBuilderFromJsonObject() {
        assertNotNull(AdverseEvent.AdverseEventSuspectEntity.create(Json.createObjectBuilder().build()).build());
    }

    @Test
    public void testCopyAll() {
        final AdverseEvent.AdverseEventSuspectEntity x = AdverseEvent.AdverseEventSuspectEntity.create().build();
        final AdverseEvent.AdverseEventSuspectEntity y = AdverseEvent.AdverseEventSuspectEntity.create().copyAll(x).build();
        assertEquals(x, y);
    }

    @Test
    public void testId() {
        assertEquals("x", AdverseEvent.AdverseEventSuspectEntity.create().id("x").build().id());
    }

    @Test
    public void testExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, AdverseEvent.AdverseEventSuspectEntity.create().extension(value).build().extension());
    }

    @Test
    public void testModifierExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, AdverseEvent.AdverseEventSuspectEntity.create().modifierExtension(value).build().modifierExtension());
    }

    @Test
    public void testInstance() {
        final Reference value = Reference.create().build();
        assertEquals(value, AdverseEvent.AdverseEventSuspectEntity.create().instance(value).build().instance());
    }

    @Test
    public void testCausality() {
        final java.util.List<AdverseEvent.AdverseEventCausality> value = java.util.Collections.emptyList();
        assertEquals(value, AdverseEvent.AdverseEventSuspectEntity.create().causality(value).build().causality());
    }
}
