/*
 * Generated by com.medplum.generator.Generator
 * Do not edit manually.
 */

package com.medplum.fhir.r4.types;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.json.Json;

import org.junit.Test;

public class DataRequirementDateFilterTest {

    @Test
    public void testConstructor() {
        assertNotNull(new DataRequirement.DataRequirementDateFilter(Json.createObjectBuilder().build()));
    }

    @Test
    public void testBuilderFromJsonObject() {
        assertNotNull(DataRequirement.DataRequirementDateFilter.create(Json.createObjectBuilder().build()).build());
    }

    @Test
    public void testCopyAll() {
        final DataRequirement.DataRequirementDateFilter x = DataRequirement.DataRequirementDateFilter.create().build();
        final DataRequirement.DataRequirementDateFilter y = DataRequirement.DataRequirementDateFilter.create().copyAll(x).build();
        assertEquals(x, y);
    }

    @Test
    public void testId() {
        assertEquals("x", DataRequirement.DataRequirementDateFilter.create().id("x").build().id());
    }

    @Test
    public void testExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, DataRequirement.DataRequirementDateFilter.create().extension(value).build().extension());
    }

    @Test
    public void testModifierExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, DataRequirement.DataRequirementDateFilter.create().modifierExtension(value).build().modifierExtension());
    }

    @Test
    public void testPath() {
        assertEquals("x", DataRequirement.DataRequirementDateFilter.create().path("x").build().path());
    }

    @Test
    public void testSearchParam() {
        assertEquals("x", DataRequirement.DataRequirementDateFilter.create().searchParam("x").build().searchParam());
    }

    @Test
    public void testValueDateTime() {
        assertEquals("x", DataRequirement.DataRequirementDateFilter.create().valueDateTime("x").build().valueDateTime());
    }

    @Test
    public void testValuePeriod() {
        final Period value = Period.create().build();
        assertEquals(value, DataRequirement.DataRequirementDateFilter.create().valuePeriod(value).build().valuePeriod());
    }

    @Test
    public void testValueDuration() {
        final Duration value = Duration.create().build();
        assertEquals(value, DataRequirement.DataRequirementDateFilter.create().valueDuration(value).build().valueDuration());
    }
}
