/*
 * Generated by com.medplum.generator.Generator
 * Do not edit manually.
 */

package com.medplum.fhir.r4.types;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.json.Json;

import org.junit.Test;

public class DeviceDefinitionUdiDeviceIdentifierTest {

    @Test
    public void testConstructor() {
        assertNotNull(new DeviceDefinition.DeviceDefinitionUdiDeviceIdentifier(Json.createObjectBuilder().build()));
    }

    @Test
    public void testBuilderFromJsonObject() {
        assertNotNull(DeviceDefinition.DeviceDefinitionUdiDeviceIdentifier.create(Json.createObjectBuilder().build()).build());
    }

    @Test
    public void testCopyAll() {
        final DeviceDefinition.DeviceDefinitionUdiDeviceIdentifier x = DeviceDefinition.DeviceDefinitionUdiDeviceIdentifier.create().build();
        final DeviceDefinition.DeviceDefinitionUdiDeviceIdentifier y = DeviceDefinition.DeviceDefinitionUdiDeviceIdentifier.create().copyAll(x).build();
        assertEquals(x, y);
    }

    @Test
    public void testId() {
        assertEquals("x", DeviceDefinition.DeviceDefinitionUdiDeviceIdentifier.create().id("x").build().id());
    }

    @Test
    public void testExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, DeviceDefinition.DeviceDefinitionUdiDeviceIdentifier.create().extension(value).build().extension());
    }

    @Test
    public void testModifierExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, DeviceDefinition.DeviceDefinitionUdiDeviceIdentifier.create().modifierExtension(value).build().modifierExtension());
    }

    @Test
    public void testDeviceIdentifier() {
        assertEquals("x", DeviceDefinition.DeviceDefinitionUdiDeviceIdentifier.create().deviceIdentifier("x").build().deviceIdentifier());
    }

    @Test
    public void testIssuer() {
        final java.net.URI value = java.net.URI.create("https://www.example.com");
        assertEquals(value, DeviceDefinition.DeviceDefinitionUdiDeviceIdentifier.create().issuer(value).build().issuer());
    }

    @Test
    public void testJurisdiction() {
        final java.net.URI value = java.net.URI.create("https://www.example.com");
        assertEquals(value, DeviceDefinition.DeviceDefinitionUdiDeviceIdentifier.create().jurisdiction(value).build().jurisdiction());
    }
}
