/*
 * Generated by com.medplum.generator.Generator
 * Do not edit manually.
 */

package com.medplum.fhir.r4.types;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.json.Json;

import org.junit.Test;

public class ImplementationGuideManifestTest {

    @Test
    public void testConstructor() {
        assertNotNull(new ImplementationGuide.ImplementationGuideManifest(Json.createObjectBuilder().build()));
    }

    @Test
    public void testBuilderFromJsonObject() {
        assertNotNull(ImplementationGuide.ImplementationGuideManifest.create(Json.createObjectBuilder().build()).build());
    }

    @Test
    public void testCopyAll() {
        final ImplementationGuide.ImplementationGuideManifest x = ImplementationGuide.ImplementationGuideManifest.create().build();
        final ImplementationGuide.ImplementationGuideManifest y = ImplementationGuide.ImplementationGuideManifest.create().copyAll(x).build();
        assertEquals(x, y);
    }

    @Test
    public void testId() {
        assertEquals("x", ImplementationGuide.ImplementationGuideManifest.create().id("x").build().id());
    }

    @Test
    public void testExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, ImplementationGuide.ImplementationGuideManifest.create().extension(value).build().extension());
    }

    @Test
    public void testModifierExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, ImplementationGuide.ImplementationGuideManifest.create().modifierExtension(value).build().modifierExtension());
    }

    @Test
    public void testRendering() {
        final java.net.URI value = java.net.URI.create("https://www.example.com");
        assertEquals(value, ImplementationGuide.ImplementationGuideManifest.create().rendering(value).build().rendering());
    }

    @Test
    public void testResource() {
        final java.util.List<ImplementationGuide.ImplementationGuideResource1> value = java.util.Collections.emptyList();
        assertEquals(value, ImplementationGuide.ImplementationGuideManifest.create().resource(value).build().resource());
    }

    @Test
    public void testPage() {
        final java.util.List<ImplementationGuide.ImplementationGuidePage1> value = java.util.Collections.emptyList();
        assertEquals(value, ImplementationGuide.ImplementationGuideManifest.create().page(value).build().page());
    }

    @Test
    public void testImage() {
        final java.util.List<String> value = java.util.Collections.emptyList();
        assertEquals(value, ImplementationGuide.ImplementationGuideManifest.create().image(value).build().image());
    }

    @Test
    public void testOther() {
        final java.util.List<String> value = java.util.Collections.emptyList();
        assertEquals(value, ImplementationGuide.ImplementationGuideManifest.create().other(value).build().other());
    }
}
