/*
 * Generated by com.medplum.generator.Generator
 * Do not edit manually.
 */

package com.medplum.fhir.r4.types;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.json.Json;

import org.junit.Test;

public class InsurancePlanSpecificCostTest {

    @Test
    public void testConstructor() {
        assertNotNull(new InsurancePlan.InsurancePlanSpecificCost(Json.createObjectBuilder().build()));
    }

    @Test
    public void testBuilderFromJsonObject() {
        assertNotNull(InsurancePlan.InsurancePlanSpecificCost.create(Json.createObjectBuilder().build()).build());
    }

    @Test
    public void testCopyAll() {
        final InsurancePlan.InsurancePlanSpecificCost x = InsurancePlan.InsurancePlanSpecificCost.create().build();
        final InsurancePlan.InsurancePlanSpecificCost y = InsurancePlan.InsurancePlanSpecificCost.create().copyAll(x).build();
        assertEquals(x, y);
    }

    @Test
    public void testId() {
        assertEquals("x", InsurancePlan.InsurancePlanSpecificCost.create().id("x").build().id());
    }

    @Test
    public void testExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, InsurancePlan.InsurancePlanSpecificCost.create().extension(value).build().extension());
    }

    @Test
    public void testModifierExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, InsurancePlan.InsurancePlanSpecificCost.create().modifierExtension(value).build().modifierExtension());
    }

    @Test
    public void testCategory() {
        final CodeableConcept value = CodeableConcept.create().build();
        assertEquals(value, InsurancePlan.InsurancePlanSpecificCost.create().category(value).build().category());
    }

    @Test
    public void testBenefit() {
        final java.util.List<InsurancePlan.InsurancePlanBenefit1> value = java.util.Collections.emptyList();
        assertEquals(value, InsurancePlan.InsurancePlanSpecificCost.create().benefit(value).build().benefit());
    }
}
