/*
 * Generated by com.medplum.generator.Generator
 * Do not edit manually.
 */

package com.medplum.fhir.r4.types;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.json.Json;

import org.junit.Test;

public class SupplyRequestParameterTest {

    @Test
    public void testConstructor() {
        assertNotNull(new SupplyRequest.SupplyRequestParameter(Json.createObjectBuilder().build()));
    }

    @Test
    public void testBuilderFromJsonObject() {
        assertNotNull(SupplyRequest.SupplyRequestParameter.create(Json.createObjectBuilder().build()).build());
    }

    @Test
    public void testCopyAll() {
        final SupplyRequest.SupplyRequestParameter x = SupplyRequest.SupplyRequestParameter.create().build();
        final SupplyRequest.SupplyRequestParameter y = SupplyRequest.SupplyRequestParameter.create().copyAll(x).build();
        assertEquals(x, y);
    }

    @Test
    public void testId() {
        assertEquals("x", SupplyRequest.SupplyRequestParameter.create().id("x").build().id());
    }

    @Test
    public void testExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, SupplyRequest.SupplyRequestParameter.create().extension(value).build().extension());
    }

    @Test
    public void testModifierExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, SupplyRequest.SupplyRequestParameter.create().modifierExtension(value).build().modifierExtension());
    }

    @Test
    public void testCode() {
        final CodeableConcept value = CodeableConcept.create().build();
        assertEquals(value, SupplyRequest.SupplyRequestParameter.create().code(value).build().code());
    }

    @Test
    public void testValueCodeableConcept() {
        final CodeableConcept value = CodeableConcept.create().build();
        assertEquals(value, SupplyRequest.SupplyRequestParameter.create().valueCodeableConcept(value).build().valueCodeableConcept());
    }

    @Test
    public void testValueQuantity() {
        final Quantity value = Quantity.create().build();
        assertEquals(value, SupplyRequest.SupplyRequestParameter.create().valueQuantity(value).build().valueQuantity());
    }

    @Test
    public void testValueRange() {
        final Range value = Range.create().build();
        assertEquals(value, SupplyRequest.SupplyRequestParameter.create().valueRange(value).build().valueRange());
    }

    @Test
    public void testValueBoolean() {
        assertEquals(true, SupplyRequest.SupplyRequestParameter.create().valueBoolean(true).build().valueBoolean());
    }
}
