/*
 * Generated by com.medplum.generator.Generator
 * Do not edit manually.
 */

package com.medplum.fhir.r4.types;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.json.Json;

import org.junit.Test;

public class TestReportOperationTest {

    @Test
    public void testConstructor() {
        assertNotNull(new TestReport.TestReportOperation(Json.createObjectBuilder().build()));
    }

    @Test
    public void testBuilderFromJsonObject() {
        assertNotNull(TestReport.TestReportOperation.create(Json.createObjectBuilder().build()).build());
    }

    @Test
    public void testCopyAll() {
        final TestReport.TestReportOperation x = TestReport.TestReportOperation.create().build();
        final TestReport.TestReportOperation y = TestReport.TestReportOperation.create().copyAll(x).build();
        assertEquals(x, y);
    }

    @Test
    public void testId() {
        assertEquals("x", TestReport.TestReportOperation.create().id("x").build().id());
    }

    @Test
    public void testExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, TestReport.TestReportOperation.create().extension(value).build().extension());
    }

    @Test
    public void testModifierExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, TestReport.TestReportOperation.create().modifierExtension(value).build().modifierExtension());
    }

    @Test
    public void testResult() {
        assertEquals("x", TestReport.TestReportOperation.create().result("x").build().result());
    }

    @Test
    public void testMessage() {
        assertEquals("x", TestReport.TestReportOperation.create().message("x").build().message());
    }

    @Test
    public void testDetail() {
        final java.net.URI value = java.net.URI.create("https://www.example.com");
        assertEquals(value, TestReport.TestReportOperation.create().detail(value).build().detail());
    }
}
