export const HEALTHIE_IDENTIFIER_SYSTEM = 'https://www.gethealthie.com';
export const HEALTHIE_USER_ID_SYSTEM = `${HEALTHIE_IDENTIFIER_SYSTEM}/userId`;
export const HEALTHIE_MEDICATION_ID_SYSTEM = `${HEALTHIE_IDENTIFIER_SYSTEM}/medicationId`;
export const HEALTHIE_MEDICATION_CODE_SYSTEM = `${HEALTHIE_IDENTIFIER_SYSTEM}/medicationCode`;
