/*
 * Generated by @medplum/generator
 * Do not edit manually.
 */

import { Repository } from '../../fhir/repo';

export async function run(_repo: Repository): Promise<void> {
  // The first data migration is a no-op.
  // This only exists to verify the data migration functionality.
}
