// SPDX-FileCopyrightText: Copyright Orangebot, Inc. and Medplum contributors
// SPDX-License-Identifier: Apache-2.0
import type { Token } from '../fhirlexer/tokenize';
import { Tokenizer } from '../fhirlexer/tokenize';
import { FHIRPATH_KEYWORDS, FHIRPATH_OPERATORS } from '../fhirpath/tokenize';

const CQL_KEYWORDS = [
  ...FHIRPATH_KEYWORDS,
  'after',
  'aggregate',
  'all',
  'and',
  'as',
  'asc',
  'ascending',
  'before',
  'between',
  'bind',
  'by',
  'called',
  'case',
  'cast',
  'Choice',
  'code',
  'Code',
  'codesystem',
  'codesystems',
  'collapse',
  'concept',
  'Concept',
  '~contains',
  'contains',
  'context',
  'conversion',
  'convert',
  'date',
  'day',
  'days',
  'default',
  'define',
  'desc',
  'descending',
  'difference',
  'display',
  'distinct',
  'div',
  'duration',
  'during',
  'else',
  'end',
  'ends',
  'except',
  'exists',
  'expand',
  'explicit',
  'extends',
  'false',
  'flatten',
  'fluent',
  'from',
  'function',
  'hour',
  'hours',
  'identifier',
  'if',
  'implicit',
  'implies',
  '~in',
  'in',
  'include',
  'includes',
  'included in',
  'intersect',
  'Interval',
  'is',
  'key',
  'label',
  'let',
  'library',
  'List',
  'maximum',
  'meets',
  'millisecond',
  'milliseconds',
  'minimum',
  'minute',
  'minutes',
  'mod',
  'month',
  'months',
  'not',
  'null',
  'occurs',
  'of',
  'on or',
  'or',
  'ordered',
  'or after',
  'or before',
  'or less',
  'or more',
  'or on',
  'overlaps',
  'parameter',
  'path',
  'per',
  'point',
  'predecessor',
  'primary',
  'private',
  'properly',
  'public',
  'related',
  'retrievable',
  'return',
  'same',
  'second',
  'seconds',
  'singleton',
  'start',
  'starting',
  'starts',
  'sort',
  'successor',
  'such that',
  'then',
  'time',
  'timezoneoffset',
  'to',
  'true',
  'Tuple',
  'type',
  'union',
  'using',
  'valueset',
  'version',
  'week',
  'weeks',
  'where',
  'when',
  'width',
  'with',
  'within',
  'without',
  'xor',
  'year',
  'years',
];
const CQL_OPERATORS = [...FHIRPATH_OPERATORS, '->', '<<', '>>', '=='];

export function tokenize(str: string): Token[] {
  return new Tokenizer(str, CQL_KEYWORDS, CQL_OPERATORS).tokenize();
}
