Instance: resources
InstanceOf: Bundle
Usage: #example
* meta.lastUpdated = "2019-11-01T09:29:23.356+11:00"
* type = #collection
* entry[0].fullUrl = "https://medplum.com/fhir/StructureDefinition/Project"
* entry[=].resource = Project
* entry[+].fullUrl = "https://medplum.com/fhir/StructureDefinition/ClientApplication"
* entry[=].resource = ClientApplication
* entry[+].fullUrl = "https://medplum.com/fhir/StructureDefinition/User"
* entry[=].resource = User
* entry[+].fullUrl = "https://medplum.com/fhir/StructureDefinition/ProjectMembership"
* entry[=].resource = ProjectMembership
* entry[+].fullUrl = "https://medplum.com/fhir/StructureDefinition/Bot"
* entry[=].resource = Bot
* entry[+].fullUrl = "https://medplum.com/fhir/StructureDefinition/Login"
* entry[=].resource = Login
* entry[+].fullUrl = "https://medplum.com/fhir/StructureDefinition/UserSecurityRequest"
* entry[=].resource = UserSecurityRequest
* entry[+].fullUrl = "https://medplum.com/fhir/StructureDefinition/JsonWebKey"
* entry[=].resource = JsonWebKey
* entry[+].fullUrl = "https://medplum.com/fhir/StructureDefinition/AccessPolicy"
* entry[=].resource = AccessPolicy
* entry[+].fullUrl = "https://medplum.com/fhir/StructureDefinition/UserConfiguration"
* entry[=].resource = UserConfiguration
* entry[+].fullUrl = "https://medplum.com/fhir/StructureDefinition/BulkDataExport"
* entry[=].resource = BulkDataExport
* entry[+].fullUrl = "https://medplum.com/fhir/StructureDefinition/SmartAppLaunch"
* entry[=].resource = SmartAppLaunch
* entry[+].fullUrl = "https://medplum.com/fhir/StructureDefinition/DomainConfiguration"
* entry[=].resource = DomainConfiguration
* entry[+].fullUrl = "https://medplum.com/fhir/StructureDefinition/IdentityProvider"
* entry[=].resource = IdentityProvider
* entry[+].fullUrl = "https://medplum.com/fhir/StructureDefinition/AsyncJob"
* entry[=].resource = AsyncJob
* entry[+].fullUrl = "https://medplum.com/fhir/StructureDefinition/Agent"
* entry[=].resource = Agent
* entry[+].fullUrl = "http://hl7.org/fhir/uv/sql-on-fhir/StructureDefinition/ViewDefinition"
* entry[=].resource = ViewDefinition