/*
 * Generated by @medplum/generator
 * Do not edit manually.
 */

import { PoolClient } from 'pg';

export async function run(client: PoolClient): Promise<void> {
  await client.query('ALTER TABLE "Account" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Account" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Account" ("projectId")');
  await client.query('CREATE INDEX ON "Account" ("fhirId")');
  await client.query('UPDATE "Account" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ActivityDefinition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ActivityDefinition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ActivityDefinition" ("projectId")');
  await client.query('CREATE INDEX ON "ActivityDefinition" ("fhirId")');
  await client.query('UPDATE "ActivityDefinition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "AdverseEvent" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "AdverseEvent" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "AdverseEvent" ("projectId")');
  await client.query('CREATE INDEX ON "AdverseEvent" ("fhirId")');
  await client.query('UPDATE "AdverseEvent" SET "fhirId"="id"');

  await client.query('ALTER TABLE "AllergyIntolerance" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "AllergyIntolerance" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "AllergyIntolerance" ("projectId")');
  await client.query('CREATE INDEX ON "AllergyIntolerance" ("fhirId")');
  await client.query('UPDATE "AllergyIntolerance" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Appointment" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Appointment" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Appointment" ("projectId")');
  await client.query('CREATE INDEX ON "Appointment" ("fhirId")');
  await client.query('UPDATE "Appointment" SET "fhirId"="id"');

  await client.query('ALTER TABLE "AppointmentResponse" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "AppointmentResponse" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "AppointmentResponse" ("projectId")');
  await client.query('CREATE INDEX ON "AppointmentResponse" ("fhirId")');
  await client.query('UPDATE "AppointmentResponse" SET "fhirId"="id"');

  await client.query('ALTER TABLE "AuditEvent" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "AuditEvent" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "AuditEvent" ("projectId")');
  await client.query('CREATE INDEX ON "AuditEvent" ("fhirId")');
  await client.query('UPDATE "AuditEvent" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Basic" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Basic" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Basic" ("projectId")');
  await client.query('CREATE INDEX ON "Basic" ("fhirId")');
  await client.query('UPDATE "Basic" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Binary" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Binary" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Binary" ("projectId")');
  await client.query('CREATE INDEX ON "Binary" ("fhirId")');
  await client.query('UPDATE "Binary" SET "fhirId"="id"');

  await client.query('ALTER TABLE "BiologicallyDerivedProduct" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "BiologicallyDerivedProduct" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "BiologicallyDerivedProduct" ("projectId")');
  await client.query('CREATE INDEX ON "BiologicallyDerivedProduct" ("fhirId")');
  await client.query('UPDATE "BiologicallyDerivedProduct" SET "fhirId"="id"');

  await client.query('ALTER TABLE "BodyStructure" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "BodyStructure" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "BodyStructure" ("projectId")');
  await client.query('CREATE INDEX ON "BodyStructure" ("fhirId")');
  await client.query('UPDATE "BodyStructure" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Bundle" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Bundle" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Bundle" ("projectId")');
  await client.query('CREATE INDEX ON "Bundle" ("fhirId")');
  await client.query('UPDATE "Bundle" SET "fhirId"="id"');

  await client.query('ALTER TABLE "CapabilityStatement" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "CapabilityStatement" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "CapabilityStatement" ("projectId")');
  await client.query('CREATE INDEX ON "CapabilityStatement" ("fhirId")');
  await client.query('UPDATE "CapabilityStatement" SET "fhirId"="id"');

  await client.query('ALTER TABLE "CarePlan" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "CarePlan" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "CarePlan" ("projectId")');
  await client.query('CREATE INDEX ON "CarePlan" ("fhirId")');
  await client.query('UPDATE "CarePlan" SET "fhirId"="id"');

  await client.query('ALTER TABLE "CareTeam" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "CareTeam" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "CareTeam" ("projectId")');
  await client.query('CREATE INDEX ON "CareTeam" ("fhirId")');
  await client.query('UPDATE "CareTeam" SET "fhirId"="id"');

  await client.query('ALTER TABLE "CatalogEntry" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "CatalogEntry" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "CatalogEntry" ("projectId")');
  await client.query('CREATE INDEX ON "CatalogEntry" ("fhirId")');
  await client.query('UPDATE "CatalogEntry" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ChargeItem" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ChargeItem" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ChargeItem" ("projectId")');
  await client.query('CREATE INDEX ON "ChargeItem" ("fhirId")');
  await client.query('UPDATE "ChargeItem" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ChargeItemDefinition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ChargeItemDefinition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ChargeItemDefinition" ("projectId")');
  await client.query('CREATE INDEX ON "ChargeItemDefinition" ("fhirId")');
  await client.query('UPDATE "ChargeItemDefinition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Claim" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Claim" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Claim" ("projectId")');
  await client.query('CREATE INDEX ON "Claim" ("fhirId")');
  await client.query('UPDATE "Claim" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ClaimResponse" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ClaimResponse" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ClaimResponse" ("projectId")');
  await client.query('CREATE INDEX ON "ClaimResponse" ("fhirId")');
  await client.query('UPDATE "ClaimResponse" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ClinicalImpression" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ClinicalImpression" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ClinicalImpression" ("projectId")');
  await client.query('CREATE INDEX ON "ClinicalImpression" ("fhirId")');
  await client.query('UPDATE "ClinicalImpression" SET "fhirId"="id"');

  await client.query('ALTER TABLE "CodeSystem" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "CodeSystem" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "CodeSystem" ("projectId")');
  await client.query('CREATE INDEX ON "CodeSystem" ("fhirId")');
  await client.query('UPDATE "CodeSystem" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Communication" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Communication" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Communication" ("projectId")');
  await client.query('CREATE INDEX ON "Communication" ("fhirId")');
  await client.query('UPDATE "Communication" SET "fhirId"="id"');

  await client.query('ALTER TABLE "CommunicationRequest" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "CommunicationRequest" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "CommunicationRequest" ("projectId")');
  await client.query('CREATE INDEX ON "CommunicationRequest" ("fhirId")');
  await client.query('UPDATE "CommunicationRequest" SET "fhirId"="id"');

  await client.query('ALTER TABLE "CompartmentDefinition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "CompartmentDefinition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "CompartmentDefinition" ("projectId")');
  await client.query('CREATE INDEX ON "CompartmentDefinition" ("fhirId")');
  await client.query('UPDATE "CompartmentDefinition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Composition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Composition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Composition" ("projectId")');
  await client.query('CREATE INDEX ON "Composition" ("fhirId")');
  await client.query('UPDATE "Composition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ConceptMap" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ConceptMap" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ConceptMap" ("projectId")');
  await client.query('CREATE INDEX ON "ConceptMap" ("fhirId")');
  await client.query('UPDATE "ConceptMap" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Condition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Condition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Condition" ("projectId")');
  await client.query('CREATE INDEX ON "Condition" ("fhirId")');
  await client.query('UPDATE "Condition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Consent" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Consent" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Consent" ("projectId")');
  await client.query('CREATE INDEX ON "Consent" ("fhirId")');
  await client.query('UPDATE "Consent" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Contract" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Contract" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Contract" ("projectId")');
  await client.query('CREATE INDEX ON "Contract" ("fhirId")');
  await client.query('UPDATE "Contract" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Coverage" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Coverage" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Coverage" ("projectId")');
  await client.query('CREATE INDEX ON "Coverage" ("fhirId")');
  await client.query('UPDATE "Coverage" SET "fhirId"="id"');

  await client.query('ALTER TABLE "CoverageEligibilityRequest" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "CoverageEligibilityRequest" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "CoverageEligibilityRequest" ("projectId")');
  await client.query('CREATE INDEX ON "CoverageEligibilityRequest" ("fhirId")');
  await client.query('UPDATE "CoverageEligibilityRequest" SET "fhirId"="id"');

  await client.query('ALTER TABLE "CoverageEligibilityResponse" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "CoverageEligibilityResponse" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "CoverageEligibilityResponse" ("projectId")');
  await client.query('CREATE INDEX ON "CoverageEligibilityResponse" ("fhirId")');
  await client.query('UPDATE "CoverageEligibilityResponse" SET "fhirId"="id"');

  await client.query('ALTER TABLE "DetectedIssue" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "DetectedIssue" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "DetectedIssue" ("projectId")');
  await client.query('CREATE INDEX ON "DetectedIssue" ("fhirId")');
  await client.query('UPDATE "DetectedIssue" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Device" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Device" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Device" ("projectId")');
  await client.query('CREATE INDEX ON "Device" ("fhirId")');
  await client.query('UPDATE "Device" SET "fhirId"="id"');

  await client.query('ALTER TABLE "DeviceDefinition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "DeviceDefinition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "DeviceDefinition" ("projectId")');
  await client.query('CREATE INDEX ON "DeviceDefinition" ("fhirId")');
  await client.query('UPDATE "DeviceDefinition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "DeviceMetric" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "DeviceMetric" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "DeviceMetric" ("projectId")');
  await client.query('CREATE INDEX ON "DeviceMetric" ("fhirId")');
  await client.query('UPDATE "DeviceMetric" SET "fhirId"="id"');

  await client.query('ALTER TABLE "DeviceRequest" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "DeviceRequest" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "DeviceRequest" ("projectId")');
  await client.query('CREATE INDEX ON "DeviceRequest" ("fhirId")');
  await client.query('UPDATE "DeviceRequest" SET "fhirId"="id"');

  await client.query('ALTER TABLE "DeviceUseStatement" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "DeviceUseStatement" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "DeviceUseStatement" ("projectId")');
  await client.query('CREATE INDEX ON "DeviceUseStatement" ("fhirId")');
  await client.query('UPDATE "DeviceUseStatement" SET "fhirId"="id"');

  await client.query('ALTER TABLE "DiagnosticReport" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "DiagnosticReport" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "DiagnosticReport" ("projectId")');
  await client.query('CREATE INDEX ON "DiagnosticReport" ("fhirId")');
  await client.query('UPDATE "DiagnosticReport" SET "fhirId"="id"');

  await client.query('ALTER TABLE "DocumentManifest" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "DocumentManifest" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "DocumentManifest" ("projectId")');
  await client.query('CREATE INDEX ON "DocumentManifest" ("fhirId")');
  await client.query('UPDATE "DocumentManifest" SET "fhirId"="id"');

  await client.query('ALTER TABLE "DocumentReference" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "DocumentReference" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "DocumentReference" ("projectId")');
  await client.query('CREATE INDEX ON "DocumentReference" ("fhirId")');
  await client.query('UPDATE "DocumentReference" SET "fhirId"="id"');

  await client.query('ALTER TABLE "EffectEvidenceSynthesis" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "EffectEvidenceSynthesis" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "EffectEvidenceSynthesis" ("projectId")');
  await client.query('CREATE INDEX ON "EffectEvidenceSynthesis" ("fhirId")');
  await client.query('UPDATE "EffectEvidenceSynthesis" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Encounter" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Encounter" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Encounter" ("projectId")');
  await client.query('CREATE INDEX ON "Encounter" ("fhirId")');
  await client.query('UPDATE "Encounter" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Endpoint" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Endpoint" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Endpoint" ("projectId")');
  await client.query('CREATE INDEX ON "Endpoint" ("fhirId")');
  await client.query('UPDATE "Endpoint" SET "fhirId"="id"');

  await client.query('ALTER TABLE "EnrollmentRequest" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "EnrollmentRequest" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "EnrollmentRequest" ("projectId")');
  await client.query('CREATE INDEX ON "EnrollmentRequest" ("fhirId")');
  await client.query('UPDATE "EnrollmentRequest" SET "fhirId"="id"');

  await client.query('ALTER TABLE "EnrollmentResponse" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "EnrollmentResponse" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "EnrollmentResponse" ("projectId")');
  await client.query('CREATE INDEX ON "EnrollmentResponse" ("fhirId")');
  await client.query('UPDATE "EnrollmentResponse" SET "fhirId"="id"');

  await client.query('ALTER TABLE "EpisodeOfCare" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "EpisodeOfCare" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "EpisodeOfCare" ("projectId")');
  await client.query('CREATE INDEX ON "EpisodeOfCare" ("fhirId")');
  await client.query('UPDATE "EpisodeOfCare" SET "fhirId"="id"');

  await client.query('ALTER TABLE "EventDefinition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "EventDefinition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "EventDefinition" ("projectId")');
  await client.query('CREATE INDEX ON "EventDefinition" ("fhirId")');
  await client.query('UPDATE "EventDefinition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Evidence" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Evidence" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Evidence" ("projectId")');
  await client.query('CREATE INDEX ON "Evidence" ("fhirId")');
  await client.query('UPDATE "Evidence" SET "fhirId"="id"');

  await client.query('ALTER TABLE "EvidenceVariable" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "EvidenceVariable" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "EvidenceVariable" ("projectId")');
  await client.query('CREATE INDEX ON "EvidenceVariable" ("fhirId")');
  await client.query('UPDATE "EvidenceVariable" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ExampleScenario" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ExampleScenario" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ExampleScenario" ("projectId")');
  await client.query('CREATE INDEX ON "ExampleScenario" ("fhirId")');
  await client.query('UPDATE "ExampleScenario" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ExplanationOfBenefit" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ExplanationOfBenefit" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ExplanationOfBenefit" ("projectId")');
  await client.query('CREATE INDEX ON "ExplanationOfBenefit" ("fhirId")');
  await client.query('UPDATE "ExplanationOfBenefit" SET "fhirId"="id"');

  await client.query('ALTER TABLE "FamilyMemberHistory" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "FamilyMemberHistory" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "FamilyMemberHistory" ("projectId")');
  await client.query('CREATE INDEX ON "FamilyMemberHistory" ("fhirId")');
  await client.query('UPDATE "FamilyMemberHistory" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Flag" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Flag" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Flag" ("projectId")');
  await client.query('CREATE INDEX ON "Flag" ("fhirId")');
  await client.query('UPDATE "Flag" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Goal" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Goal" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Goal" ("projectId")');
  await client.query('CREATE INDEX ON "Goal" ("fhirId")');
  await client.query('UPDATE "Goal" SET "fhirId"="id"');

  await client.query('ALTER TABLE "GraphDefinition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "GraphDefinition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "GraphDefinition" ("projectId")');
  await client.query('CREATE INDEX ON "GraphDefinition" ("fhirId")');
  await client.query('UPDATE "GraphDefinition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Group" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Group" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Group" ("projectId")');
  await client.query('CREATE INDEX ON "Group" ("fhirId")');
  await client.query('UPDATE "Group" SET "fhirId"="id"');

  await client.query('ALTER TABLE "GuidanceResponse" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "GuidanceResponse" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "GuidanceResponse" ("projectId")');
  await client.query('CREATE INDEX ON "GuidanceResponse" ("fhirId")');
  await client.query('UPDATE "GuidanceResponse" SET "fhirId"="id"');

  await client.query('ALTER TABLE "HealthcareService" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "HealthcareService" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "HealthcareService" ("projectId")');
  await client.query('CREATE INDEX ON "HealthcareService" ("fhirId")');
  await client.query('UPDATE "HealthcareService" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ImagingStudy" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ImagingStudy" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ImagingStudy" ("projectId")');
  await client.query('CREATE INDEX ON "ImagingStudy" ("fhirId")');
  await client.query('UPDATE "ImagingStudy" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Immunization" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Immunization" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Immunization" ("projectId")');
  await client.query('CREATE INDEX ON "Immunization" ("fhirId")');
  await client.query('UPDATE "Immunization" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ImmunizationEvaluation" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ImmunizationEvaluation" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ImmunizationEvaluation" ("projectId")');
  await client.query('CREATE INDEX ON "ImmunizationEvaluation" ("fhirId")');
  await client.query('UPDATE "ImmunizationEvaluation" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ImmunizationRecommendation" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ImmunizationRecommendation" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ImmunizationRecommendation" ("projectId")');
  await client.query('CREATE INDEX ON "ImmunizationRecommendation" ("fhirId")');
  await client.query('UPDATE "ImmunizationRecommendation" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ImplementationGuide" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ImplementationGuide" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ImplementationGuide" ("projectId")');
  await client.query('CREATE INDEX ON "ImplementationGuide" ("fhirId")');
  await client.query('UPDATE "ImplementationGuide" SET "fhirId"="id"');

  await client.query('ALTER TABLE "InsurancePlan" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "InsurancePlan" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "InsurancePlan" ("projectId")');
  await client.query('CREATE INDEX ON "InsurancePlan" ("fhirId")');
  await client.query('UPDATE "InsurancePlan" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Invoice" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Invoice" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Invoice" ("projectId")');
  await client.query('CREATE INDEX ON "Invoice" ("fhirId")');
  await client.query('UPDATE "Invoice" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Library" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Library" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Library" ("projectId")');
  await client.query('CREATE INDEX ON "Library" ("fhirId")');
  await client.query('UPDATE "Library" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Linkage" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Linkage" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Linkage" ("projectId")');
  await client.query('CREATE INDEX ON "Linkage" ("fhirId")');
  await client.query('UPDATE "Linkage" SET "fhirId"="id"');

  await client.query('ALTER TABLE "List" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "List" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "List" ("projectId")');
  await client.query('CREATE INDEX ON "List" ("fhirId")');
  await client.query('UPDATE "List" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Location" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Location" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Location" ("projectId")');
  await client.query('CREATE INDEX ON "Location" ("fhirId")');
  await client.query('UPDATE "Location" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Measure" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Measure" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Measure" ("projectId")');
  await client.query('CREATE INDEX ON "Measure" ("fhirId")');
  await client.query('UPDATE "Measure" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MeasureReport" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MeasureReport" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MeasureReport" ("projectId")');
  await client.query('CREATE INDEX ON "MeasureReport" ("fhirId")');
  await client.query('UPDATE "MeasureReport" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Media" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Media" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Media" ("projectId")');
  await client.query('CREATE INDEX ON "Media" ("fhirId")');
  await client.query('UPDATE "Media" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Medication" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Medication" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Medication" ("projectId")');
  await client.query('CREATE INDEX ON "Medication" ("fhirId")');
  await client.query('UPDATE "Medication" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MedicationAdministration" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MedicationAdministration" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MedicationAdministration" ("projectId")');
  await client.query('CREATE INDEX ON "MedicationAdministration" ("fhirId")');
  await client.query('UPDATE "MedicationAdministration" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MedicationDispense" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MedicationDispense" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MedicationDispense" ("projectId")');
  await client.query('CREATE INDEX ON "MedicationDispense" ("fhirId")');
  await client.query('UPDATE "MedicationDispense" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MedicationKnowledge" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MedicationKnowledge" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MedicationKnowledge" ("projectId")');
  await client.query('CREATE INDEX ON "MedicationKnowledge" ("fhirId")');
  await client.query('UPDATE "MedicationKnowledge" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MedicationRequest" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MedicationRequest" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MedicationRequest" ("projectId")');
  await client.query('CREATE INDEX ON "MedicationRequest" ("fhirId")');
  await client.query('UPDATE "MedicationRequest" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MedicationStatement" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MedicationStatement" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MedicationStatement" ("projectId")');
  await client.query('CREATE INDEX ON "MedicationStatement" ("fhirId")');
  await client.query('UPDATE "MedicationStatement" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MedicinalProduct" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MedicinalProduct" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MedicinalProduct" ("projectId")');
  await client.query('CREATE INDEX ON "MedicinalProduct" ("fhirId")');
  await client.query('UPDATE "MedicinalProduct" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MedicinalProductAuthorization" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MedicinalProductAuthorization" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MedicinalProductAuthorization" ("projectId")');
  await client.query('CREATE INDEX ON "MedicinalProductAuthorization" ("fhirId")');
  await client.query('UPDATE "MedicinalProductAuthorization" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MedicinalProductContraindication" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MedicinalProductContraindication" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MedicinalProductContraindication" ("projectId")');
  await client.query('CREATE INDEX ON "MedicinalProductContraindication" ("fhirId")');
  await client.query('UPDATE "MedicinalProductContraindication" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MedicinalProductIndication" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MedicinalProductIndication" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MedicinalProductIndication" ("projectId")');
  await client.query('CREATE INDEX ON "MedicinalProductIndication" ("fhirId")');
  await client.query('UPDATE "MedicinalProductIndication" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MedicinalProductIngredient" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MedicinalProductIngredient" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MedicinalProductIngredient" ("projectId")');
  await client.query('CREATE INDEX ON "MedicinalProductIngredient" ("fhirId")');
  await client.query('UPDATE "MedicinalProductIngredient" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MedicinalProductInteraction" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MedicinalProductInteraction" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MedicinalProductInteraction" ("projectId")');
  await client.query('CREATE INDEX ON "MedicinalProductInteraction" ("fhirId")');
  await client.query('UPDATE "MedicinalProductInteraction" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MedicinalProductManufactured" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MedicinalProductManufactured" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MedicinalProductManufactured" ("projectId")');
  await client.query('CREATE INDEX ON "MedicinalProductManufactured" ("fhirId")');
  await client.query('UPDATE "MedicinalProductManufactured" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MedicinalProductPackaged" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MedicinalProductPackaged" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MedicinalProductPackaged" ("projectId")');
  await client.query('CREATE INDEX ON "MedicinalProductPackaged" ("fhirId")');
  await client.query('UPDATE "MedicinalProductPackaged" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MedicinalProductPharmaceutical" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MedicinalProductPharmaceutical" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MedicinalProductPharmaceutical" ("projectId")');
  await client.query('CREATE INDEX ON "MedicinalProductPharmaceutical" ("fhirId")');
  await client.query('UPDATE "MedicinalProductPharmaceutical" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MedicinalProductUndesirableEffect" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MedicinalProductUndesirableEffect" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MedicinalProductUndesirableEffect" ("projectId")');
  await client.query('CREATE INDEX ON "MedicinalProductUndesirableEffect" ("fhirId")');
  await client.query('UPDATE "MedicinalProductUndesirableEffect" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MessageDefinition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MessageDefinition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MessageDefinition" ("projectId")');
  await client.query('CREATE INDEX ON "MessageDefinition" ("fhirId")');
  await client.query('UPDATE "MessageDefinition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MessageHeader" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MessageHeader" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MessageHeader" ("projectId")');
  await client.query('CREATE INDEX ON "MessageHeader" ("fhirId")');
  await client.query('UPDATE "MessageHeader" SET "fhirId"="id"');

  await client.query('ALTER TABLE "MolecularSequence" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "MolecularSequence" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "MolecularSequence" ("projectId")');
  await client.query('CREATE INDEX ON "MolecularSequence" ("fhirId")');
  await client.query('UPDATE "MolecularSequence" SET "fhirId"="id"');

  await client.query('ALTER TABLE "NamingSystem" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "NamingSystem" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "NamingSystem" ("projectId")');
  await client.query('CREATE INDEX ON "NamingSystem" ("fhirId")');
  await client.query('UPDATE "NamingSystem" SET "fhirId"="id"');

  await client.query('ALTER TABLE "NutritionOrder" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "NutritionOrder" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "NutritionOrder" ("projectId")');
  await client.query('CREATE INDEX ON "NutritionOrder" ("fhirId")');
  await client.query('UPDATE "NutritionOrder" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Observation" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Observation" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Observation" ("projectId")');
  await client.query('CREATE INDEX ON "Observation" ("fhirId")');
  await client.query('UPDATE "Observation" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ObservationDefinition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ObservationDefinition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ObservationDefinition" ("projectId")');
  await client.query('CREATE INDEX ON "ObservationDefinition" ("fhirId")');
  await client.query('UPDATE "ObservationDefinition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "OperationDefinition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "OperationDefinition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "OperationDefinition" ("projectId")');
  await client.query('CREATE INDEX ON "OperationDefinition" ("fhirId")');
  await client.query('UPDATE "OperationDefinition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "OperationOutcome" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "OperationOutcome" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "OperationOutcome" ("projectId")');
  await client.query('CREATE INDEX ON "OperationOutcome" ("fhirId")');
  await client.query('UPDATE "OperationOutcome" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Organization" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Organization" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Organization" ("projectId")');
  await client.query('CREATE INDEX ON "Organization" ("fhirId")');
  await client.query('UPDATE "Organization" SET "fhirId"="id"');

  await client.query('ALTER TABLE "OrganizationAffiliation" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "OrganizationAffiliation" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "OrganizationAffiliation" ("projectId")');
  await client.query('CREATE INDEX ON "OrganizationAffiliation" ("fhirId")');
  await client.query('UPDATE "OrganizationAffiliation" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Parameters" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Parameters" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Parameters" ("projectId")');
  await client.query('CREATE INDEX ON "Parameters" ("fhirId")');
  await client.query('UPDATE "Parameters" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Patient" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Patient" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Patient" ("projectId")');
  await client.query('CREATE INDEX ON "Patient" ("fhirId")');
  await client.query('UPDATE "Patient" SET "fhirId"="id"');

  await client.query('ALTER TABLE "PaymentNotice" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "PaymentNotice" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "PaymentNotice" ("projectId")');
  await client.query('CREATE INDEX ON "PaymentNotice" ("fhirId")');
  await client.query('UPDATE "PaymentNotice" SET "fhirId"="id"');

  await client.query('ALTER TABLE "PaymentReconciliation" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "PaymentReconciliation" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "PaymentReconciliation" ("projectId")');
  await client.query('CREATE INDEX ON "PaymentReconciliation" ("fhirId")');
  await client.query('UPDATE "PaymentReconciliation" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Person" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Person" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Person" ("projectId")');
  await client.query('CREATE INDEX ON "Person" ("fhirId")');
  await client.query('UPDATE "Person" SET "fhirId"="id"');

  await client.query('ALTER TABLE "PlanDefinition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "PlanDefinition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "PlanDefinition" ("projectId")');
  await client.query('CREATE INDEX ON "PlanDefinition" ("fhirId")');
  await client.query('UPDATE "PlanDefinition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Practitioner" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Practitioner" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Practitioner" ("projectId")');
  await client.query('CREATE INDEX ON "Practitioner" ("fhirId")');
  await client.query('UPDATE "Practitioner" SET "fhirId"="id"');

  await client.query('ALTER TABLE "PractitionerRole" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "PractitionerRole" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "PractitionerRole" ("projectId")');
  await client.query('CREATE INDEX ON "PractitionerRole" ("fhirId")');
  await client.query('UPDATE "PractitionerRole" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Procedure" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Procedure" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Procedure" ("projectId")');
  await client.query('CREATE INDEX ON "Procedure" ("fhirId")');
  await client.query('UPDATE "Procedure" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Provenance" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Provenance" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Provenance" ("projectId")');
  await client.query('CREATE INDEX ON "Provenance" ("fhirId")');
  await client.query('UPDATE "Provenance" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Questionnaire" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Questionnaire" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Questionnaire" ("projectId")');
  await client.query('CREATE INDEX ON "Questionnaire" ("fhirId")');
  await client.query('UPDATE "Questionnaire" SET "fhirId"="id"');

  await client.query('ALTER TABLE "QuestionnaireResponse" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "QuestionnaireResponse" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "QuestionnaireResponse" ("projectId")');
  await client.query('CREATE INDEX ON "QuestionnaireResponse" ("fhirId")');
  await client.query('UPDATE "QuestionnaireResponse" SET "fhirId"="id"');

  await client.query('ALTER TABLE "RelatedPerson" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "RelatedPerson" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "RelatedPerson" ("projectId")');
  await client.query('CREATE INDEX ON "RelatedPerson" ("fhirId")');
  await client.query('UPDATE "RelatedPerson" SET "fhirId"="id"');

  await client.query('ALTER TABLE "RequestGroup" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "RequestGroup" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "RequestGroup" ("projectId")');
  await client.query('CREATE INDEX ON "RequestGroup" ("fhirId")');
  await client.query('UPDATE "RequestGroup" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ResearchDefinition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ResearchDefinition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ResearchDefinition" ("projectId")');
  await client.query('CREATE INDEX ON "ResearchDefinition" ("fhirId")');
  await client.query('UPDATE "ResearchDefinition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ResearchElementDefinition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ResearchElementDefinition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ResearchElementDefinition" ("projectId")');
  await client.query('CREATE INDEX ON "ResearchElementDefinition" ("fhirId")');
  await client.query('UPDATE "ResearchElementDefinition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ResearchStudy" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ResearchStudy" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ResearchStudy" ("projectId")');
  await client.query('CREATE INDEX ON "ResearchStudy" ("fhirId")');
  await client.query('UPDATE "ResearchStudy" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ResearchSubject" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ResearchSubject" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ResearchSubject" ("projectId")');
  await client.query('CREATE INDEX ON "ResearchSubject" ("fhirId")');
  await client.query('UPDATE "ResearchSubject" SET "fhirId"="id"');

  await client.query('ALTER TABLE "RiskAssessment" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "RiskAssessment" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "RiskAssessment" ("projectId")');
  await client.query('CREATE INDEX ON "RiskAssessment" ("fhirId")');
  await client.query('UPDATE "RiskAssessment" SET "fhirId"="id"');

  await client.query('ALTER TABLE "RiskEvidenceSynthesis" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "RiskEvidenceSynthesis" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "RiskEvidenceSynthesis" ("projectId")');
  await client.query('CREATE INDEX ON "RiskEvidenceSynthesis" ("fhirId")');
  await client.query('UPDATE "RiskEvidenceSynthesis" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Schedule" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Schedule" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Schedule" ("projectId")');
  await client.query('CREATE INDEX ON "Schedule" ("fhirId")');
  await client.query('UPDATE "Schedule" SET "fhirId"="id"');

  await client.query('ALTER TABLE "SearchParameter" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "SearchParameter" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "SearchParameter" ("projectId")');
  await client.query('CREATE INDEX ON "SearchParameter" ("fhirId")');
  await client.query('UPDATE "SearchParameter" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ServiceRequest" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ServiceRequest" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ServiceRequest" ("projectId")');
  await client.query('CREATE INDEX ON "ServiceRequest" ("fhirId")');
  await client.query('UPDATE "ServiceRequest" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Slot" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Slot" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Slot" ("projectId")');
  await client.query('CREATE INDEX ON "Slot" ("fhirId")');
  await client.query('UPDATE "Slot" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Specimen" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Specimen" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Specimen" ("projectId")');
  await client.query('CREATE INDEX ON "Specimen" ("fhirId")');
  await client.query('UPDATE "Specimen" SET "fhirId"="id"');

  await client.query('ALTER TABLE "SpecimenDefinition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "SpecimenDefinition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "SpecimenDefinition" ("projectId")');
  await client.query('CREATE INDEX ON "SpecimenDefinition" ("fhirId")');
  await client.query('UPDATE "SpecimenDefinition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "StructureDefinition" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "StructureDefinition" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "StructureDefinition" ("projectId")');
  await client.query('CREATE INDEX ON "StructureDefinition" ("fhirId")');
  await client.query('UPDATE "StructureDefinition" SET "fhirId"="id"');

  await client.query('ALTER TABLE "StructureMap" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "StructureMap" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "StructureMap" ("projectId")');
  await client.query('CREATE INDEX ON "StructureMap" ("fhirId")');
  await client.query('UPDATE "StructureMap" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Subscription" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Subscription" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Subscription" ("projectId")');
  await client.query('CREATE INDEX ON "Subscription" ("fhirId")');
  await client.query('UPDATE "Subscription" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Substance" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Substance" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Substance" ("projectId")');
  await client.query('CREATE INDEX ON "Substance" ("fhirId")');
  await client.query('UPDATE "Substance" SET "fhirId"="id"');

  await client.query('ALTER TABLE "SubstanceNucleicAcid" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "SubstanceNucleicAcid" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "SubstanceNucleicAcid" ("projectId")');
  await client.query('CREATE INDEX ON "SubstanceNucleicAcid" ("fhirId")');
  await client.query('UPDATE "SubstanceNucleicAcid" SET "fhirId"="id"');

  await client.query('ALTER TABLE "SubstancePolymer" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "SubstancePolymer" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "SubstancePolymer" ("projectId")');
  await client.query('CREATE INDEX ON "SubstancePolymer" ("fhirId")');
  await client.query('UPDATE "SubstancePolymer" SET "fhirId"="id"');

  await client.query('ALTER TABLE "SubstanceProtein" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "SubstanceProtein" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "SubstanceProtein" ("projectId")');
  await client.query('CREATE INDEX ON "SubstanceProtein" ("fhirId")');
  await client.query('UPDATE "SubstanceProtein" SET "fhirId"="id"');

  await client.query('ALTER TABLE "SubstanceReferenceInformation" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "SubstanceReferenceInformation" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "SubstanceReferenceInformation" ("projectId")');
  await client.query('CREATE INDEX ON "SubstanceReferenceInformation" ("fhirId")');
  await client.query('UPDATE "SubstanceReferenceInformation" SET "fhirId"="id"');

  await client.query('ALTER TABLE "SubstanceSourceMaterial" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "SubstanceSourceMaterial" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "SubstanceSourceMaterial" ("projectId")');
  await client.query('CREATE INDEX ON "SubstanceSourceMaterial" ("fhirId")');
  await client.query('UPDATE "SubstanceSourceMaterial" SET "fhirId"="id"');

  await client.query('ALTER TABLE "SubstanceSpecification" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "SubstanceSpecification" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "SubstanceSpecification" ("projectId")');
  await client.query('CREATE INDEX ON "SubstanceSpecification" ("fhirId")');
  await client.query('UPDATE "SubstanceSpecification" SET "fhirId"="id"');

  await client.query('ALTER TABLE "SupplyDelivery" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "SupplyDelivery" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "SupplyDelivery" ("projectId")');
  await client.query('CREATE INDEX ON "SupplyDelivery" ("fhirId")');
  await client.query('UPDATE "SupplyDelivery" SET "fhirId"="id"');

  await client.query('ALTER TABLE "SupplyRequest" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "SupplyRequest" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "SupplyRequest" ("projectId")');
  await client.query('CREATE INDEX ON "SupplyRequest" ("fhirId")');
  await client.query('UPDATE "SupplyRequest" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Task" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Task" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Task" ("projectId")');
  await client.query('CREATE INDEX ON "Task" ("fhirId")');
  await client.query('UPDATE "Task" SET "fhirId"="id"');

  await client.query('ALTER TABLE "TerminologyCapabilities" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "TerminologyCapabilities" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "TerminologyCapabilities" ("projectId")');
  await client.query('CREATE INDEX ON "TerminologyCapabilities" ("fhirId")');
  await client.query('UPDATE "TerminologyCapabilities" SET "fhirId"="id"');

  await client.query('ALTER TABLE "TestReport" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "TestReport" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "TestReport" ("projectId")');
  await client.query('CREATE INDEX ON "TestReport" ("fhirId")');
  await client.query('UPDATE "TestReport" SET "fhirId"="id"');

  await client.query('ALTER TABLE "TestScript" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "TestScript" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "TestScript" ("projectId")');
  await client.query('CREATE INDEX ON "TestScript" ("fhirId")');
  await client.query('UPDATE "TestScript" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ValueSet" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ValueSet" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ValueSet" ("projectId")');
  await client.query('CREATE INDEX ON "ValueSet" ("fhirId")');
  await client.query('UPDATE "ValueSet" SET "fhirId"="id"');

  await client.query('ALTER TABLE "VerificationResult" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "VerificationResult" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "VerificationResult" ("projectId")');
  await client.query('CREATE INDEX ON "VerificationResult" ("fhirId")');
  await client.query('UPDATE "VerificationResult" SET "fhirId"="id"');

  await client.query('ALTER TABLE "VisionPrescription" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "VisionPrescription" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "VisionPrescription" ("projectId")');
  await client.query('CREATE INDEX ON "VisionPrescription" ("fhirId")');
  await client.query('UPDATE "VisionPrescription" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Project" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Project" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Project" ("projectId")');
  await client.query('CREATE INDEX ON "Project" ("fhirId")');
  await client.query('UPDATE "Project" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ClientApplication" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ClientApplication" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ClientApplication" ("projectId")');
  await client.query('CREATE INDEX ON "ClientApplication" ("fhirId")');
  await client.query('UPDATE "ClientApplication" SET "fhirId"="id"');

  await client.query('ALTER TABLE "User" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "User" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "User" ("projectId")');
  await client.query('CREATE INDEX ON "User" ("fhirId")');
  await client.query('UPDATE "User" SET "fhirId"="id"');

  await client.query('ALTER TABLE "ProjectMembership" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "ProjectMembership" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "ProjectMembership" ("projectId")');
  await client.query('CREATE INDEX ON "ProjectMembership" ("fhirId")');
  await client.query('UPDATE "ProjectMembership" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Bot" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Bot" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Bot" ("projectId")');
  await client.query('CREATE INDEX ON "Bot" ("fhirId")');
  await client.query('UPDATE "Bot" SET "fhirId"="id"');

  await client.query('ALTER TABLE "Login" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "Login" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "Login" ("projectId")');
  await client.query('CREATE INDEX ON "Login" ("fhirId")');
  await client.query('UPDATE "Login" SET "fhirId"="id"');

  await client.query('ALTER TABLE "PasswordChangeRequest" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "PasswordChangeRequest" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "PasswordChangeRequest" ("projectId")');
  await client.query('CREATE INDEX ON "PasswordChangeRequest" ("fhirId")');
  await client.query('UPDATE "PasswordChangeRequest" SET "fhirId"="id"');

  await client.query('ALTER TABLE "JsonWebKey" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "JsonWebKey" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "JsonWebKey" ("projectId")');
  await client.query('CREATE INDEX ON "JsonWebKey" ("fhirId")');
  await client.query('UPDATE "JsonWebKey" SET "fhirId"="id"');

  await client.query('ALTER TABLE "AccessPolicy" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "AccessPolicy" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "AccessPolicy" ("projectId")');
  await client.query('CREATE INDEX ON "AccessPolicy" ("fhirId")');
  await client.query('UPDATE "AccessPolicy" SET "fhirId"="id"');

  await client.query('ALTER TABLE "UserConfiguration" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "UserConfiguration" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "UserConfiguration" ("projectId")');
  await client.query('CREATE INDEX ON "UserConfiguration" ("fhirId")');
  await client.query('UPDATE "UserConfiguration" SET "fhirId"="id"');

  await client.query('ALTER TABLE "BulkDataExport" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "BulkDataExport" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "BulkDataExport" ("projectId")');
  await client.query('CREATE INDEX ON "BulkDataExport" ("fhirId")');
  await client.query('UPDATE "BulkDataExport" SET "fhirId"="id"');

  await client.query('ALTER TABLE "SmartAppLaunch" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "SmartAppLaunch" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "SmartAppLaunch" ("projectId")');
  await client.query('CREATE INDEX ON "SmartAppLaunch" ("fhirId")');
  await client.query('UPDATE "SmartAppLaunch" SET "fhirId"="id"');

  await client.query('ALTER TABLE "DomainConfiguration" ADD COLUMN "projectId" UUID');
  await client.query('ALTER TABLE "DomainConfiguration" ADD COLUMN "fhirId" TEXT');
  await client.query('CREATE INDEX ON "DomainConfiguration" ("projectId")');
  await client.query('CREATE INDEX ON "DomainConfiguration" ("fhirId")');
  await client.query('UPDATE "DomainConfiguration" SET "fhirId"="id"');
}
