/*
 * Generated by @medplum/generator
 * Do not edit manually.
 */

import { PoolClient } from 'pg';

export async function run(client: PoolClient): Promise<void> {
  await client.query(`CREATE TABLE IF NOT EXISTS "Bot" (
    "id" UUID NOT NULL PRIMARY KEY,
    "content" TEXT NOT NULL,
    "lastUpdated" TIMESTAMP WITH TIME ZONE NOT NULL,
    "compartments" UUID[] NOT NULL,
    "name" TEXT
  )`);

  await client.query(`CREATE TABLE IF NOT EXISTS "Bot_History" (
    "versionId" UUID NOT NULL PRIMARY KEY,
    "id" UUID NOT NULL,
    "content" TEXT NOT NULL,
    "lastUpdated" TIMESTAMP WITH TIME ZONE NOT NULL
  )`);
}
