# Default values for medplum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: medplum

global:
  cloudProvider: gcp
  gcp:
    projectId: [MY_PROJECT_ID] # Your Google Cloud Platform project ID
    secretId: [MY_CONFIG_SECRET_ID] # The secret ID for configuration in Google Cloud Platform
 
deployment:
  replicaCount: 1
  image:
    repository: medplum/medplum-server
    tag: latest

  autoscaling:
    enabled: true

# service:
#   port: 80
#   targetPort: 8103

ingress:
  deploy: true
  domain: api.example.com
  
serviceAccount: 
  annotations:
    iam.gke.io/gcp-service-account: [MY_GCP_SERVICE_ACCOUNT] # Your Google Cloud Platform service account e.i: medplum-server@[MY_PROJECT_ID].iam.gserviceaccount.com
  