# Default values for medplum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: medplum

global:
  domain: api.zencore.medplum.dev
  cloudProvider: gcp

image:
  # repository: medplum/medplum-server
  repository: us-west1-docker.pkg.dev/medplum-zencore/medplum-repo/medplum-server
  pullPolicy: IfNotPresent
  tag: test3

env:
  - name: POSTGRES_HOST
    value: "POSTGRES_IP_ADDRESS" # obtain from GCP secret
  - name: POSTGRES_PORT
    value: "5432"
  - name: SHOULD_RUN_SEED_TEST
    value: "true"
  - name: REDIS_PASSWORD_DISABLED_IN_TESTS
    value: "true"

  - name: DATABASE_URL
    value:
  - name: REDIS_URL
    value: "redis://redis-instance-ip:6379"
  - name: POSTGRES_USER
    value: "medplum"
  - name: POSTGRES_PASSWORD
    value:
  - name: POSTGRES_DB
    value: "your-database-name"
  - name: REDIS_HOST
    value: "MEMORYSTORE_PRIVATE_IP"
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_PASSWORD
    value: "medplum"

serviceAccount:
  create: true
  automount: true
  annotations:
    iam.gke.io/gcp-service-account: medplum-server@medplum-zencore.iam.gserviceaccount.com

service:
  type: ClusterIP
  port: 8103

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: medplum-external-ip
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"8103":"medplum-backend-config"}}'
  path: /
  pathType: Prefix
  tls: false

  backendConfig:
    healthCheck:
      port: 8103
      requestPath: /healthcheck

  frontendConfig: 
    redirectToHttps:
      enabled: true
      responseCodeName: RESPONSE_CODE
  
  managedCertificate:
    create: true

livenessProbe:
  httpGet:
    path: /healthcheck
    port: 8103
readinessProbe:
  httpGet:
    path: /healthcheck
    port: 8103
resources:
  limits:
    memory: "512Mi"
  requests:
    memory: "256Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
