# Default values for medplum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: medplum

global:
  domain: api.zencore.medplum.dev
  cloudProvider: gcp

gcp:
  projectId: medplum-zencore
  secretId: config-diego-test

# aws:
#   region: us-west-2


image:
  # repository: medplum/medplum-server
  repository: us-west1-docker.pkg.dev/medplum-zencore/medplum-repo/medplum-server
  pullPolicy: IfNotPresent
  tag: test3

serviceAccount:
  create: true
  automount: true
  annotations:
    iam.gke.io/gcp-service-account: medplum-server@medplum-zencore.iam.gserviceaccount.com

service:
  type: ClusterIP
  port: 8103

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: medplum-external-ip
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"8103":"medplum-backend-config"}}'
  path: /
  pathType: Prefix
  tls: false

  backendConfig:
    healthCheck:
      port: 8103
      requestPath: /healthcheck

  frontendConfig: 
    redirectToHttps:
      enabled: true
      responseCodeName: RESPONSE_CODE
  
  managedCertificate:
    create: true

livenessProbe:
  httpGet:
    path: /healthcheck
    port: 8103
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 30
readinessProbe:
  httpGet:
    path: /healthcheck
    port: 8103
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 30

resources:
  limits:
    memory: "512Mi"
  requests:
    memory: "256Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
