# Default values for medplum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: medplum

global:
  cloudProvider: gcp
  gcp:
    projectId: medplum-zencore
    secretId: config-diego-test
 
deployment:
  replicaCount: 1
  image:
    # repository: medplum/medplum-server
    repository: us-west1-docker.pkg.dev/medplum-zencore/medplum-repo/medplum-server
    tag: test4
  autoscaling:
    enabled: true

service:
  port: 80

ingress:
  deploy: true
  domain: api.zencore.medplum.dev
  
serviceAccount: 
  annotations:
    iam.gke.io/gcp-service-account: medplum-server@medplum-zencore.iam.gserviceaccount.com
  