/*
 * Generated by com.medplum.generator.Generator
 * Do not edit manually.
 */

package com.medplum.fhir.types;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.Test;

public class CountTest {

    @Test
    public void testId() {
        assertEquals("x", Count.create().id("x").build().id());
    }

    @Test
    public void testValue() {
        assertEquals(1.0, Count.create().value(1.0).build().value());
    }

    @Test
    public void testComparator() {
        assertEquals("x", Count.create().comparator("x").build().comparator());
    }

    @Test
    public void testUnit() {
        assertEquals("x", Count.create().unit("x").build().unit());
    }

    @Test
    public void testSystem() {
        assertEquals("x", Count.create().system("x").build().system());
    }

    @Test
    public void testCode() {
        assertEquals("x", Count.create().code("x").build().code());
    }
}
