/*
 * Generated by com.medplum.generator.Generator
 * Do not edit manually.
 */

package com.medplum.fhir.types;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.Test;

public class DiagnosticReportMediaTest {

    @Test
    public void testId() {
        assertEquals("x", DiagnosticReport.DiagnosticReportMedia.create().id("x").build().id());
    }

    @Test
    public void testModifierExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, DiagnosticReport.DiagnosticReportMedia.create().modifierExtension(value).build().modifierExtension());
    }

    @Test
    public void testComment() {
        assertEquals("x", DiagnosticReport.DiagnosticReportMedia.create().comment("x").build().comment());
    }

    @Test
    public void testLink() {
        final Reference value = Reference.create().build();
        assertEquals(value, DiagnosticReport.DiagnosticReportMedia.create().link(value).build().link());
    }
}
