/*
 * Generated by com.medplum.generator.Generator
 * Do not edit manually.
 */

package com.medplum.fhir.types;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.Test;

public class PersonLinkTest {

    @Test
    public void testId() {
        assertEquals("x", Person.PersonLink.create().id("x").build().id());
    }

    @Test
    public void testModifierExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, Person.PersonLink.create().modifierExtension(value).build().modifierExtension());
    }

    @Test
    public void testTarget() {
        final Reference value = Reference.create().build();
        assertEquals(value, Person.PersonLink.create().target(value).build().target());
    }

    @Test
    public void testAssurance() {
        assertEquals("x", Person.PersonLink.create().assurance("x").build().assurance());
    }
}
