/*
 * Generated by com.medplum.generator.Generator
 * Do not edit manually.
 */

package com.medplum.fhir.types;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.json.Json;

import org.junit.Test;

public class RefreshTokenTest {

    @Test
    public void testConstructor() {
        assertNotNull(new RefreshToken(Json.createObjectBuilder().build()));
    }

    @Test
    public void testBuilderFromJsonObject() {
        assertNotNull(RefreshToken.create(Json.createObjectBuilder().build()).build());
    }

    @Test
    public void testResourceType() {
        assertEquals("x", RefreshToken.create().resourceType("x").build().resourceType());
    }

    @Test
    public void testId() {
        assertEquals("x", RefreshToken.create().id("x").build().id());
    }

    @Test
    public void testClient() {
        final Reference value = Reference.create().build();
        assertEquals(value, RefreshToken.create().client(value).build().client());
    }

    @Test
    public void testUser() {
        final Reference value = Reference.create().build();
        assertEquals(value, RefreshToken.create().user(value).build().user());
    }

    @Test
    public void testScope() {
        assertEquals("x", RefreshToken.create().scope("x").build().scope());
    }
}
