/*
 * Generated by com.medplum.generator.Generator
 * Do not edit manually.
 */

package com.medplum.fhir.types;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.Test;

public class RiskEvidenceSynthesisSampleSizeTest {

    @Test
    public void testId() {
        assertEquals("x", RiskEvidenceSynthesis.RiskEvidenceSynthesisSampleSize.create().id("x").build().id());
    }

    @Test
    public void testModifierExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, RiskEvidenceSynthesis.RiskEvidenceSynthesisSampleSize.create().modifierExtension(value).build().modifierExtension());
    }

    @Test
    public void testDescription() {
        assertEquals("x", RiskEvidenceSynthesis.RiskEvidenceSynthesisSampleSize.create().description("x").build().description());
    }

    @Test
    public void testNumberOfStudies() {
        assertEquals(1, RiskEvidenceSynthesis.RiskEvidenceSynthesisSampleSize.create().numberOfStudies(1).build().numberOfStudies());
    }

    @Test
    public void testNumberOfParticipants() {
        assertEquals(1, RiskEvidenceSynthesis.RiskEvidenceSynthesisSampleSize.create().numberOfParticipants(1).build().numberOfParticipants());
    }
}
