/*
 * Generated by com.medplum.generator.Generator
 * Do not edit manually.
 */

package com.medplum.fhir.types;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.Test;

public class SpecimenDefinitionHandlingTest {

    @Test
    public void testId() {
        assertEquals("x", SpecimenDefinition.SpecimenDefinitionHandling.create().id("x").build().id());
    }

    @Test
    public void testModifierExtension() {
        final java.util.List<Extension> value = java.util.Collections.emptyList();
        assertEquals(value, SpecimenDefinition.SpecimenDefinitionHandling.create().modifierExtension(value).build().modifierExtension());
    }

    @Test
    public void testTemperatureQualifier() {
        final CodeableConcept value = CodeableConcept.create().build();
        assertEquals(value, SpecimenDefinition.SpecimenDefinitionHandling.create().temperatureQualifier(value).build().temperatureQualifier());
    }

    @Test
    public void testTemperatureRange() {
        final Range value = Range.create().build();
        assertEquals(value, SpecimenDefinition.SpecimenDefinitionHandling.create().temperatureRange(value).build().temperatureRange());
    }

    @Test
    public void testMaxDuration() {
        final Duration value = Duration.create().build();
        assertEquals(value, SpecimenDefinition.SpecimenDefinitionHandling.create().maxDuration(value).build().maxDuration());
    }

    @Test
    public void testInstruction() {
        assertEquals("x", SpecimenDefinition.SpecimenDefinitionHandling.create().instruction("x").build().instruction());
    }
}
