// SPDX-FileCopyrightText: Copyright Orangebot, Inc. and Medplum contributors
// SPDX-License-Identifier: Apache-2.0

// Re-export DoseSpot constants from @medplum/dosespot-core
export {
  DOSESPOT_ADD_FAVORITE_MEDICATION_BOT,
  DOSESPOT_ADD_PATIENT_PHARMACY_BOT,
  DOSESPOT_CLINIC_FAVORITE_ID_SYSTEM,
  DOSESPOT_DISPENSABLE_DRUG_ID_SYSTEM,
  DOSESPOT_GET_FAVORITE_MEDICATIONS_BOT,
  DOSESPOT_IFRAME_BOT,
  DOSESPOT_MEDICATION_HISTORY_BOT,
  DOSESPOT_NOTIFICATION_COUNTS_BOT,
  DOSESPOT_PATIENT_ID_SYSTEM,
  DOSESPOT_PATIENT_SYNC_BOT,
  DOSESPOT_PHARMACY_ID_SYSTEM,
  DOSESPOT_PRESCRIPTIONS_SYNC_BOT,
  DOSESPOT_SEARCH_MEDICATIONS_BOT,
  DOSESPOT_SEARCH_PHARMACY_BOT,
  MEDPLUM_BOT_SYSTEM,
} from '@medplum/dosespot-core';
export type { DoseSpotNotificationCountsResponse } from '@medplum/dosespot-core';
