name: Add issue to projects

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened

permissions:
  contents: read

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@1b844f0c5ac6446a402e0cb3693f9be5eca188c5 # v0.6.1
        with:
          project-url: https://github.com/orgs/medplum/projects/1
          github-token: ${{ secrets.MEDPLUM_BOT_GITHUB_ACCESS_TOKEN }}
      - uses: actions/add-to-project@1b844f0c5ac6446a402e0cb3693f9be5eca188c5 # v0.6.1
        with:
          project-url: https://github.com/orgs/medplum/projects/3
          github-token: ${{ secrets.MEDPLUM_BOT_GITHUB_ACCESS_TOKEN }}
          labeled: customer
