name: Assign pull request

on:
  pull_request:
    types: [opened]

jobs:
  assign-pull-request:
    name: Assign pull request
    runs-on: ubuntu-latest
    steps:
      - name: Assign pull request
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            if (pr.data.assignees.length === 0) {
              try {
                await github.rest.issues.checkUserCanBeAssigned({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  assignee: context.actor,
                });

                await github.rest.issues.addAssignees({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  assignees: [context.actor],
                });
              } catch (err) {
                console.error(`Cannot assign PR #${context.issue.number} to ${context.actor}: ${err.message}`);
              }
            }
