name: Build Helm Charts

concurrency:
  group: ci-build-helm-${{ github.sha }}
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          # After v6, the default for `package-manager-cache` is true. We however, have historically used caching with a fallback which is not supported by the setup-node action
          # See: https://github.com/actions/setup-node/issues/328
          package-manager-cache: false

      - name: Setup Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: 'v4.2.1'

      - name: Setup Helm S3
        run: helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.17.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Import GPG key
        run: echo "${{ secrets.MEDPLUM_GPG_KEY }}" | gpg --batch --no-tty --import

      - name: Add Medplum S3 Helm repository
        run: helm repo add medplum-s3 s3://charts.medplum.com --force-update

      - name: Get Chart Version and File Name
        id: get_chart_info
        run: |
          CHART_NAME="medplum"
          CHART_VERSION=$(node -p "require('./package.json').version")
          CHART_FILE="${CHART_NAME}-${CHART_VERSION}.tgz"
          echo "CHART_FILE=$CHART_FILE" >> $GITHUB_OUTPUT

      - name: Package the Helm charts
        run: helm package ./charts

      - name: Push the chart to S3
        run: helm s3 push ${{ steps.get_chart_info.outputs.CHART_FILE }} medplum-s3 --relative
