name: Build deb

concurrency:
  group: ci-build-deb-${{ github.sha }}
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_deb:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      NODE_VERSION: '22'
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_CACHE: 'remote:rw'
    permissions:
      actions: read
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          # After v6, the default for `package-manager-cache` is true. We however, have historically used caching with a fallback which is not supported by the setup-node action
          # See: https://github.com/actions/setup-node/issues/328
          package-manager-cache: false

      - name: Cache node modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:fast
        env:
          MEDPLUM_BASE_URL: '__MEDPLUM_BASE_URL__'
          MEDPLUM_CLIENT_ID: '__MEDPLUM_CLIENT_ID__'
          MEDPLUM_REGISTER_ENABLED: '__MEDPLUM_REGISTER_ENABLED__'
          GOOGLE_CLIENT_ID: '__GOOGLE_CLIENT_ID__'
          RECAPTCHA_SITE_KEY: '__RECAPTCHA_SITE_KEY__'

      - name: Build Deb
        shell: bash
        run: ./scripts/build-deb.sh

      - name: Set up Ruby
        uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          ruby-version: '4.0.5'

      - name: Install deb-s3
        run: gem install deb-s3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Import GPG key
        run: echo "${{ secrets.MEDPLUM_GPG_KEY }}" | gpg --batch --no-tty --import

      - name: Upload to APT repository
        run: |
          deb-s3 upload \
            --bucket apt.medplum.com \
            --prefix debian \
            --component main \
            --visibility nil \
            --preserve-versions \
            --sign=${{ secrets.MEDPLUM_GPG_KEY_ID }} \
            --gpg-options="--passphrase-fd 0 --pinentry-mode loopback" \
            --cache-control="max-age=300" \
            medplum_*.deb \
            < <(echo "${{ secrets.MEDPLUM_GPG_PASSPHRASE }}")
