name: Jira Ticket ID Validator

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-jira-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Validate commit messages for Jira Ticket ID
        uses: actions/github-script@v7
        with:
          script: |
            const commits = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const jiraRegex = /\bWAD-\d+\b/; // Strictly match WAD-123

            const invalid = commits.data.filter(commit => {
              const msg = commit.commit.message;
              return !jiraRegex.test(msg);
            });

            if (invalid.length > 0) {
              const errorList = invalid.map(c => `• ${c.commit.message}`).join('\n');
              core.setFailed(`❌ The following commits are missing a valid Jira ticket ID (e.g., WAD-123):\n${errorList}`);
            } else {
              console.log("✅ All commit messages include valid Jira ticket IDs.");
            }