# Borrowed from: https://github.com/oven-sh/bun/blob/main/.github/workflows/prettier-fmt.yml
name: prettier

concurrency:
  group: ci-prettier-${{ github.ref_name == 'main' && github.sha || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - derrick/test-actions

jobs:
  prettier-fmt:
    name: prettier
    runs-on: ubuntu-latest
    outputs:
      prettier_fmt_errs: ${{ steps.fmt.outputs.prettier_fmt_errs }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - id: install
        name: Install prettier
        run: npm ci
      - name: Run prettier
        id: fmt
        run: |
          rm -f .failed
          npx prettier --check "**/*.{ts,tsx,cts,mts,js,jsx,cjs,mjs}" 2> prettier-fmt.err > prettier-fmt1.err || echo 'failed' > .failed 

          if [ -s .failed ]; then
            delimiter="$(openssl rand -hex 8)"
            echo "prettier_fmt_errs<<${delimiter}" >> "${GITHUB_OUTPUT}"
            cat prettier-fmt.err >> "${GITHUB_OUTPUT}"
            cat prettier-fmt1.err >> "${GITHUB_OUTPUT}"
            echo "${delimiter}" >> "${GITHUB_OUTPUT}"
          fi
      - name: Comment on PR
        if: steps.fmt.outputs.prettier_fmt_errs != ''
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: prettier-fmt
          message: |
            ❌ @${{ github.actor }} `prettier` reported errors

            ```js
            ${{ steps.fmt.outputs.prettier_fmt_errs }}
            ```

            To one-off fix this manually, run:
            ```sh
            npm run prettier
            ```

            You might need to run `npm install` locally and configure your text editor to [auto-format on save](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode).

            <sup>[#${{github.sha}}](https://github.com/medplum/medplum/commits/${{github.sha}})</sup>
      - name: Uncomment on PR
        if: steps.fmt.outputs.prettier_fmt_errs == ''
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: prettier-fmt
          mode: upsert
          create_if_not_exists: false
          message: |
            ✅ `prettier` errors have been resolved. Thank you.

            <sup>[#${{github.sha}}](https://github.com/medplum/medplum/commits/${{github.sha}})</sup>
      - name: Fail the job
        if: steps.fmt.outputs.prettier_fmt_errs != ''
        run: |
          echo "❌ \"prettier\" reported errors"
          echo ""
          echo "To one-off fix this manually, run:"
          echo ""
          echo "npm run prettier"
          echo ""
          echo ""
          echo "You might need to run \"npm install\" locally and configure your text editor to auto-format on save."
          echo "See: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode"
          echo ""
          echo "https://github.com/medplum/medplum/commits/${{github.sha}}"
          
          exit 1
