# Borrowed from: https://github.com/oven-sh/bun/blob/main/.github/workflows/prettier-fmt.yml
name: prettier

concurrency:
  group: ci-prettier-${{ github.ref_name == 'main' && github.sha || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - derrick/test-actions

jobs:
  prettier-fmt:
    name: prettier
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    outputs:
      prettier_fmt_errs: ${{ steps.fmt.outputs.prettier_fmt_errs }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - id: install
        name: Install prettier
        run: npm ci --maxsockets 1
      - name: Run prettier
        id: fmt
        run: |
          rm -f .failed
          npx prettier --check "**/*.{ts,tsx,cts,mts,js,jsx,cjs,mjs}" 2> prettier-fmt.err > prettier-fmt1.err || echo 'failed' > .failed 

          if [ -s .failed ]; then
            delimiter="$(openssl rand -hex 8)"
            echo "prettier_fmt_errs<<${delimiter}" >> "${GITHUB_OUTPUT}"
            cat prettier-fmt.err >> "${GITHUB_OUTPUT}"
            cat prettier-fmt1.err >> "${GITHUB_OUTPUT}"
            echo "${delimiter}" >> "${GITHUB_OUTPUT}"
          fi
      - name: Fail the job
        if: steps.fmt.outputs.prettier_fmt_errs != ''
        run: |
          echo "❌ \"prettier\" reported errors"
          echo ""
          echo "${{ steps.fmt.outputs.prettier_fmt_errs }}"
          echo ""
          echo ""
          echo "To one-off fix this manually, run:"
          echo ""
          echo "npm run prettier"
          echo ""
          echo ""
          echo "You might need to run \"npm install\" locally and configure your text editor to auto-format on save."
          echo "See: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode"
          echo ""
          echo "https://github.com/medplum/medplum/commits/${{github.sha}}"

          exit 1
