name: Renovate

on:
  schedule:
    # Every Monday at 9:00 AM UTC
    # Every Monday at 1:00 AM PST (2:00 AM PDT)
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log level'
        required: false
        default: 'info'
        type: choice
        options:
          - trace
          - debug
          - info
          - warn
          - error
          - fatal

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - uses: renovatebot/github-action@8217b3fc286df088d7c27f3255fe8414463bc0fd # v46.1.15
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_GIT_AUTHOR: 'Medplum Bot <bot@medplum.com>'
          RENOVATE_ONBOARDING: 'false'
          RENOVATE_REQUIRE_CONFIG: 'required'
          RENOVATE_AUTODISCOVER: 'false'
          RENOVATE_HOST_RULES: >-
            [
              {
                "hostType": "docker",
                "matchHost": "docker.io",
                "username": "${{ secrets.DOCKERHUB_USERNAME }}",
                "password": "${{ secrets.DOCKERHUB_TOKEN }}"
              },
              {
                "hostType": "docker",
                "matchHost": "dhi.io",
                "username": "${{ secrets.DOCKERHUB_USERNAME }}",
                "password": "${{ secrets.DOCKERHUB_TOKEN }}"
              }
            ]
          LOG_LEVEL: ${{ github.event.inputs.log_level || 'info' }}
        with:
          token: ${{ secrets.MEDPLUM_BOT_GITHUB_ACCESS_TOKEN }}
