name: Renovate

on:
  schedule:
    # Every Monday at 9:00 AM UTC
    # Every Monday at 1:00 AM PST (2:00 AM PDT)
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - uses: renovatebot/github-action@8217b3fc286df088d7c27f3255fe8414463bc0fd # v46.1.15
        with:
          token: ${{ secrets.MEDPLUM_BOT_GITHUB_ACCESS_TOKEN }}
